### ISSUE TITLE
HTTPS Everywhere (secure-site switcher)

### ISSUE THREAD

**Issue by karanverma** [mozilla/TBTWBuildChallenge#10]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Security Challenger
- Challenge Contact Person Name: Karan Verma
- Campus Name: DAVIET, Jalandhar
### Idea Description

_Please answer all of the questions below._
- Idea name: HTTPS Everywhere (secure-site switcher)
- What is the problem you are solving for: This makes browsing more secure by encrypting everything from your computer to their server, and vice-versa.
- Who encounters that problem (who is your audience - describe them): Github or Campus audience.
- How will your tool solve this problem for these people:  
  The plug-in, designed for Chrome, Firefox, and Opera, is also available for Firefox for Android.
- What are you going to create (app, add-on, extension, etc.): plugin
- What are the next steps for building this tool: 
  Yes, and implement and publish it.
- Links to additional information: 

http://www.zdnet.com/pictures/the-best-privacy-tools-for-staying-safe-secure-online/14/

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @ScottDowne

**Comment by abbycabs** [comment]
Thanks for the proposal @karanverma! 

This looks like the existing project: https://www.eff.org/HTTPS-everywhere. Are you proposing to re-build this?

**Comment by karanverma** [comment]
Yup

**Comment by charissalaisy** [comment]
@karanverma, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!
