### ISSUE TITLE
SAFE BROWSING

### ISSUE THREAD

**Issue by singhalshubham89** [mozilla/TBTWBuildChallenge#11]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Privacy Boosters
- Challenge Contact Person Name:Sarvesh Tendulkar 
- Campus Name: MIT College Of Engineering Pune
### Idea Description

_Please answer all of the questions below._
- Idea name:Wifi Doctor
- What is the problem you are solving for: Public wifi which do not have security such as WPA/WPA2 and while browsing you might be tracked by hacker who is in same wifi network.
- Who encounters that problem (who is your audience - describe them): All age groups who have less knowledge about privacy.
- How will your tool solve this problem for these people:  Our tool will be Web extensions which will notify user when they are login or doing payment .It will notify user that "Its not safe to process as you are on public wifi" and we will have red strips which will alarm user that not to continue process.
- What are you going to create (app, add-on, extension, etc.): Web extensions
- What are the next steps for building this tool: Creating a prototype and final product 
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @ScottDowne

**Comment by abbycabs** [comment]
Thanks for the idea @singhalshubham89! Will your tool only be activated on public wifi networks? How will it know when you're on a safe network? I can see this being annoying if it turns on _every_ time I'm logging in!

**Comment by singhalshubham89** [comment]
Mainly the open wifi are not safe so our tool is mainly for public wifi where chances of information stealing is more.

Our extension will check wheather wifi connectivity is open or it has password protection (WPA/WPA2) and we are working upon it.

Yeah that is the whole purpose of this extension that user will be reminded every time that they are on open wifi which might be some trouble and extension will only turn on only while doing login or payment to the website after that it will stop prompting till relogin is initiated.

**Comment by charissalaisy** [comment]
@singhalshubham89, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @singhalshubham89! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
