### ISSUE TITLE
Ghostery (anti-tracking tool)

### ISSUE THREAD

**Issue by karanverma** [mozilla/TBTWBuildChallenge#12]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Security Challengers
- Challenge Contact Person Name: Karan Verma
- Campus Name: DAVIET, Jalandhar
### Idea Description

_Please answer all of the questions below._
- Idea name:Ghostery (anti-tracking tool)
- What is the problem you are solving for: From encrypted instant messengers to secure browsers and operating systems, these privacy-enhancing apps, extensions, and services can protect you both online and offline.
- Who encounters that problem (who is your audience - describe them): Facebook, linkedin group users, github and campus teams.
- How will your tool solve this problem for these people:  Ghostery is a tracking tool that can be added to your browser to show you how you're being tracked online -- and by whom. Available for most modern browsers for desktop and mobile, its aim is to inform users of how many companies are tracking your activities, like what sites you visit, and which companies collect data on you in order to serve you adverts. 
- What are you going to create (app, add-on, extension, etc.):  browser extension
- What are the next steps for building this tool: to implement as soon as.
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @ScottDowne

**Comment by karanverma** [comment]
next process ?

**Comment by abbycabs** [comment]
Hi @karanverma! How is this different from Do Not Track?: https://www.mozilla.org/en-US/firefox/dnt/

There are a few existing anti-tracking tools -- have you done any market research? Why do you need to build one?

**Comment by karanverma** [comment]
It will track the records on browser and save activity to the folder of system directory.

**Comment by charissalaisy** [comment]
@karanverma, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @karanverma! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
