### ISSUE TITLE
Safe and Sound

### ISSUE THREAD

**Issue by fenzledge** [mozilla/TBTWBuildChallenge#13]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Legionella
- Challenge Contact Person Name: 
- Campus Name: Airlangga University
### Idea Description

_Please answer all of the questions below._
- Idea name: Safe and Sound
- What is the problem you are solving for: hacking issues
- Who encounters that problem (who is your audience - describe them):  youth 
- How will your tool solve this problem for these people:  my tool provide auto-protection for the user
- What are you going to create (app, add-on, extension, etc.):  an application
- What are the next steps for building this tool: plan all the tools that needed to create the app
- Links to additional information: none

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @ScottDowne

**Comment by ScottDowne** [comment]
I think you need to elaborate a bit as to how your tool is going to provide auto-protection.

**Comment by abbycabs** [comment]
Thanks for the idea @fenzledge! I don't think I fully understand your idea, can you elaborate?

**Comment by charissalaisy** [comment]
@fenzledge 

Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @fenzledge! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
