### ISSUE TITLE
Gallery lock

### ISSUE THREAD

**Issue by ashwinvasudevan** [mozilla/TBTWBuildChallenge#15]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Easwari Engineering Collge, Firefox Students group
- Challenge Contact Person Name: Ashwin Vasudevan
- Campus Name: Easwari Engineering College
### Idea Description

_Please answer all of the questions below._
- Idea name: Gallery Lock
- What is the problem you are solving for:  Firefox OS does not have an app to properly secure pictures and personal information as of yet. We will be developing an app to protect the privacy of the users. 
- Who encounters that problem (who is your audience - describe them): Users of firefox OS phones
- How will your tool solve this problem for these people: Our will provide a numeric or pattern lock to the default gallery application. This ensures the privacy of the users. 
- What are you going to create (app, add-on, extension, etc.):  App
- What are the next steps for building this tool: Development of the app using Firefox SDK
- Links to additional information: 

http://stackoverflow.com/questions/25004383/gallery-lock-application-firefox-os

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @ScottDowne

**Comment by abbycabs** [comment]
Hey @ashwinvasudevan! Thanks for the proposal. This seems like useful functionality, but I'm not familiar enough with firefox OS to comment on the feasibility or existing alternatives.

**Comment by ashwinvasudevan** [comment]
@acabunoc Thank you for your time 
@LucyeoH How shall we proceed?

**Comment by charissalaisy** [comment]
@ashwinvasudevan thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @ashwinvasudevan! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
