### ISSUE TITLE
MAC UWindsor: ReCon for the Web

### ISSUE THREAD

**Issue by amritsinghbains** [mozilla/TBTWBuildChallenge#16]
- Team Name: MAC UWindsor
- Challenge Contact Person Name: Amrit Singh Bains
- Campus Name: University of Windsor, Canada
### Idea Description
- Idea name: ReCon for the Web
- What is the problem you are solving for: Large majority of people are unaware of the fact that their privacy information in being sent to different websites for different purposes. This can be easily tracked by checking the network calls on your web browser. A few reasons could be to show advertisement, display revelant images etc. Sometimes, there may be malicious code which sends private information not only including date of births or address but passwords associated to these accounts. With ReCon, we give you a way to see how your personal information is transmitted to other parties, and allow you to block or modify it with fine granularity.
- Who encounters that problem (who is your audience - describe them): People accessing any Website
- How will your tool solve this problem for these people:  This tool will empower people to know what information is being transmitted and to whom(to which website). In the extension there will be a "Leakiness" score given to each website, this will mark the trust factor from a user point of view towards a website.
- What are you going to create (app, add-on, extension, etc.): An app for statistic analysis and generating report for each website and an extension to detect network calls
- What are the next steps for building this tool: Learning about extensions and ReCon Project
- Links to additional information: 
  http://recon.meddle.mobi/

**Comment by drchoffnes** [comment]
This is mixing together quite a few things from our discussion. First, you should say that you would build on ReCon -- the way it sounds it seems like you are building it (and it's already built). Second, you may want to focus on a customizable "leakiness score" ranking and UI. The static analysis part we discussed is a separate project and doesn't have any system to build on, so it will be much more challenging to implement. If you do want to pursue it, I would make it a separate Build Technology goal.

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @ScottDowne

**Comment by ScottDowne** [comment]
Could be useful to have a leakiness threshold in my user settings that would block or warn before I go to a site with a leakiness factor above what I set.

**Comment by abbycabs** [comment]
Hi @amritsinghbains! Thanks for the submitting this idea!

Based on the link you added, I can't tell if the ReCon project allows for extensions or contributions. You're planning on making a web version of these native apps?

**Comment by drchoffnes** [comment]
For the record, I am their coach and I run the ReCon project, so the
extensions/contributions are very much allowed :)

I will let the team answer your other question.

**Comment by amritsinghbains** [comment]
Private Repo: https://github.com/amritsinghbains/ReCon-Web

**Comment by charissalaisy** [comment]
@amritsinghbains, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @amritsinghbains! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.

**Comment by amritsinghbains** [comment]
Thank you for the suggestions, my team will look at it very soon.
@sappybawa
@neeltrivedi

**Comment by sappybawa** [comment]
Team: @amritsinghbains  @neeltrivedi @drchoffnes [local coach]

@charissalaisy follow this up for screenshots, presentation and code. Thanks

Presentaion: https://drive.google.com/file/d/0B5XXMf-P4lF9SzVvWVQzcFBoMTg/view?pref=2&pli=1

Code: https://github.com/amritsinghbains/ReCon-Web

Screenshots:
![screenshot1](https://cloud.githubusercontent.com/assets/17070305/15909503/a4289c2e-2d94-11e6-84df-c95a63dad70d.png)
![screenshot2](https://cloud.githubusercontent.com/assets/17070305/15909502/a4289fb2-2d94-11e6-8595-a58d0595ee3b.png)
![screenshot3](https://cloud.githubusercontent.com/assets/17070305/15909500/a4277ee8-2d94-11e6-93ab-95806e3c0ea9.png)
![screenshot4](https://cloud.githubusercontent.com/assets/17070305/15909499/a4272844-2d94-11e6-92ae-d4bafb2c0d12.png)
![screenshot5](https://cloud.githubusercontent.com/assets/17070305/15909504/a42b752a-2d94-11e6-974c-68c9809614e7.png)
![screenshot6](https://cloud.githubusercontent.com/assets/17070305/15909501/a4280b9c-2d94-11e6-95a1-ff0e4be411ac.png)
