### ISSUE TITLE
MAC UWindsor: One Login

### ISSUE THREAD

**Issue by amritsinghbains** [mozilla/TBTWBuildChallenge#17]
- Team Name: MAC UWindsor
- Challenge Contact Person Name: Amrit Singh Bains
- Campus Name: University of Windsor, Canada
### Idea Description
- Idea name: One Login
- What is the problem you are solving for: Each website wants users to login into their website. therefore there is always a Register button which users are reluctant to click as one needs to enter the same demographic information to each and every website. We propose to creating a one stop shop for One Login. In this application, a user will create a profile for themselves and enter all the required information, this will include the necessary information which most registration form have in common and also website specific(genre) fields. There will be a login implementation given for different websites to use. When a user logins in using this portal, he will be informed about the fields which a particular website needs from the "One Login". For Example, "Company Abc wants to use your name, email and phone number to register you in their database. Do you want to allow access?"
- Who encounters that problem (who is your audience - describe them): People who have multiple accounts on different websites and who don't want to memorize the password for each website
- How will your tool solve this problem for these people: There will be a "Login with One Account" button which will help automate the registration process which will be secure and standardized 
- What are you going to create (app, add-on, extension, etc.): Application
- What are the next steps for building this tool: Using JS and Login Credentials using OAuth and similar technologies
- Links to additional information: 
  http://oauth.net/2/

**Comment by drchoffnes** [comment]
It's not clear to me how this is different from existing tools for Single Sign On. I'm not saying it isn't, but it's worth pointing out. Also, try to be more specific about how this improves user privacy. What if a website won't let you proceed without sharing something you don't want to share? Are there alternatives?

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @ScottDowne

**Comment by abbycabs** [comment]
Thanks for the project idea @amritsinghbains!

I agree with @drchoffnes, there seem to be some existing tools for this problem.How is this different from a password manager (like lastpass or 1password)? This sounds like a password manager with only one password.

**Comment by amritsinghbains** [comment]
We are thinking of not continuing with this project and shift our focus to https://github.com/mozilla/TBTWBuildChallenge/issues/16
