### ISSUE TITLE
Android _privacy 

### ISSUE THREAD

**Issue by aiyankovil** [mozilla/TBTWBuildChallenge#18]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: 
  MELLON 
- Challenge Contact Person Name: KURUVILLA GEORGE,STANLEY JOHNSON,AVEES JOSEPH 
- Campus Name: St Joseph of engineering and technology, Palai
### Idea Description

_Please answer all of the questions below._
- Idea name:Android privacy 
- What is the problem you are solving for: Android devices are known for its insecurity and privacy issues created due third party application. Many user's are not aware about this issue . This has created major problems. Many user data and personal information are getting shared among public without the knowledge of the user. Android give liberty to third party application to access data and information of the users. Many application have access even to your personal photos. This is major issue to brought up in case of privacy.
- Who encounters that problem (who is your audience - describe them): Android users ( major smartphone users)
- How will your tool solve this problem for these people:  The effect of the problem can be reduced by creating awareness among the users. Our app will focus on making user aware about the amount and type of data accessed by different apps. The app also suggest methods to prevent it. The tool also make user aware of problems in sharing those data to an app based on the credibility of the apps. Details of access permission given to different apps are also displayed.
- What are you going to create (app, add-on, extension, etc.): Android app
- What are the next steps for building this tool: The app is under development stage and we are now focusing on bringing notification alerts on certain privacy and security alerts. We are focusing on making the app more user friendly,so that even a child could be aware of the privacy issues.
- Links to additional information: http://www.androidauthority.com/university-of-cambridge-study-android-devices-insecure-security-updates-649086/

**Comment by LucyeoH-zz** [comment]
Reviewers: @ScottDowne @jeffbryner

**Comment by jeffbryner** [comment]
Does this app involve monitoring of the other apps installed on a device, or is this just general awareness of the permissions granted to installed apps? Where does the credibility of the app come from?

**Comment by aiyankovil** [comment]
@jeffbryner  The app focuses on applications installed on a device. It monitors the permissions granted to each app and informs the user. Our app does not transmit any user data over the network, this ensures a high level of safety.

**Comment by charissalaisy** [comment]
@aiyankovil thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @aiyankovil! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
