### ISSUE TITLE
Web Site Risk Analyzer 

### ISSUE THREAD

**Issue by sureshmadushan** [mozilla/TBTWBuildChallenge#19]
# Build Technology Idea Submission
- Team Name: Team Rajarata
- Challenge Contact Person Name: P.B.Suresh Madushan
- Campus Name: Rajarata university of Sri Lanka
### Idea Description
- Idea name: Notify Me
- What is the problem you are solving for: 
      People in the word don't know about websites what they visit. We give chance to people to give feedback about websites what they visited and others can come and see the comments, feedback and ranking of that websites. This is crowd sourceing project. people give information for people. They can worn others about visiting spesific web sites.
- Who encounters that problem (who is your audience - describe them): Everyone
- How will your tool solve this problem for these people:  People will know the risk of visiting websites. 
- What are you going to create (app, add-on, extension, etc.): Web App
- What are the next steps for building this tool: Developing Prototype.
- Links to additional information

**Comment by LucyeoH-zz** [comment]
Reviewers: @ScottDowne @jeffbryner

**Comment by jeffbryner** [comment]
Interesting, I like the crowd sourcing idea. 

How would this differ from https://www.mywot.com/

**Comment by ScottDowne** [comment]
I think an addon would make sense with a web app. That way you could open up the comments on the website you're currently on, report things, etc. You could probably make the bulk of the app a single codebase and have the addon and webapp both use it.

**Comment by sureshmadushan** [comment]
Hi ,
i will reply more information with after June 1.These days busy with
exams.sorry for late.

P.B.Suresh Madushan.
Bsc in ICT
Faculty of Applied Sciences.
Rajarata University of Sri Lanka.

**Comment by charissalaisy** [comment]
@sureshmadushan thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @sureshmadushan! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
