### ISSUE TITLE
 Build Technology Idea Submission [Hide IP]

### ISSUE THREAD

**Issue by rjrajivjha** [mozilla/TBTWBuildChallenge#2]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Wings of Fire, USICT, New Delhi, India
- Build Technology Challenge
  Contact Person Name:  Rajiv Kumar Jha
- Campus Name: University School of Information and Communication Technology
### Idea Description

_Please answer all of the questions below._
- Idea name: Hide Ip plugin
- What is the problem you are solving for: WebRTC Leak
- Who encounters that problem (who is your audience - describe them):  Those who use VPN, proxy servers. It will help them to protect their anonymity.
  WebRTC is a new communication protocol that relies on JavaScript that can leak your actual IP address from behind your VPN.
- How will your tool solve this problem for these people:  There is a manual method to disable WebRtc in firefox. My tool will automate that whole method. And as many peoples doesn't even know about where to get the information on how to disable webrtc, but lots of them do search for add-ons. This will easily help them out,
- What are you going to create (app, add-on, extension, etc.): An addon
- What are the next steps for building this tool: I will write a script to automate the process. and submit it as an add-on.
- Links to additional information: https://www.privacytools.io/#webrtc

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @brianking

**Comment by abbycabs** [comment]
Hi @rajivjhaimin, thanks for this! This sounds reasonable. Just to confirm, you want to automate the following steps?:

---

How to disable WebRTC in Firefox?

In short: Set "media.peerconnection.enabled" to "false" in "about:config".

Explained:

```
Enter "about:config" in the firefox address bar and press enter.
Press the button "I'll be careful, I promise!"
Search for "media.peerconnection.enabled"
Double click the entry, the column "Value" should now be "false"
Done. Do the WebRTC leak test again.
```

If you want to make sure every single WebRTC related setting is really disabled change these settings:

```
media.peerconnection.turn.disable = true
media.peerconnection.use_document_iceservers = false
media.peerconnection.video.enabled = false
media.peerconnection.identity.timeout = 1
```

Now you can be 100% sure WebRTC is disabled.

**Comment by brianking** [comment]
I like the idea of highlighting how WebRTC leaks, but think disabling it completely is too much in my opinion. It will break Web functionality, possible without the user being aware. One possible approach is to disable it _per site_ if possible, or at least not setting the site load based on user preferences. So as auser loads a site using WebRTC, and if they have VPN or a proxy on, they could be alerted about the possible leak and asked if they want to proceed loading the site.

**Comment by charissalaisy** [comment]
@rajivjhaimin, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype. 

A prototype can come in many different forms, some of which you can read about [here](https://novoed.com/prototyping-2016-1/). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!
