### ISSUE TITLE
Track Who Tracks You

### ISSUE THREAD

**Issue by AprilMorone** [mozilla/TBTWBuildChallenge#20]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Team Awesome
- Challenge Contact Person Name: April Morone
- Campus Name: HardvardEdX Online
### Idea Description

_Please answer all of the questions below._
- Idea name: Unveil More about The Trackers Who Track You
- What is the problem you are solving for: Improving upon the Lightbeam concept by having a browser extension that will not only show who tracks users, but that will ALSO show the certificates of all who track users, as well as show the level of security of certificates of those who track users.
- Who encounters that problem (who is your audience - describe them): All users of browser.
- How will your tool solve this problem for these people:  it will not only show who tracks users and users' activities, but it also will show those trackers' security certificates and the level of those security certificates.
- What are you going to create (app, add-on, extension, etc.): Add-on.
- What are the next steps for building this tool: 
  The use of JavaScript, RequireJS, HTML, CSS, ui.js type file, and basically taking how Lightbeam is made and coding to improve it.
- Links to additional information: 

None, yet

**Comment by LucyeoH-zz** [comment]
Reviewers: @ScottDowne @jeffbryner

**Comment by jeffbryner** [comment]
Nice enhancement idea! What is the critieria for the 'level' of certificate? Is it based on the SSL guidelines here? 
https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by ScottDowne** [comment]
Is the idea that this would be a feature added to lightbeam itself, or a new addon be created upon the lightbeam concept? Would be easier to build on lightbeam and you would also get existing users.

**Comment by AprilMorone** [comment]
ScottDowne, This idea is for a new add-on to be created upon the lightbeam concept. Good point about just building on lightbeam. I will speak with my team about joining the lightbeam team to build on lightbeam.

**Comment by AprilMorone** [comment]
jeffbryner, Thank you. :)  I think I will take ScottDowne's idea about building on lightbeam to enhance it to implement my idea.

**Comment by charissalaisy** [comment]
@AprilMorone thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @AprilMorone! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.

**Comment by AprilMorone** [comment]
Awesome, you two. Sorry that I didn't see this until after June 10th. I had been handling other personal projects, as well. Is it still too late to do this? I have now have Malik and Amit Kumar Jaiswal who want to help me in doing this.

**Comment by AprilMorone** [comment]
Thank you for these. I have built apps, websites, and software, taken computer tech courses and gotten my tech degree that included web design classes. I have Malik as a friend and designer, too, who said he will build modules and asked me to give him the name of modules for users, as well as data structures. That is at where we are in developing this, already, before putting it, here. Any extra advise about this part of the process?

**Comment by bacharakis** [comment]
Hi @AprilMorone ! 
It's OK that you missed the deadline! Do you believe you can have a prototype of your idea in the next 2 weeks?
Thank you
