### ISSUE TITLE
Privacy Report Web Application

### ISSUE THREAD

**Issue by thegtagamer** [mozilla/TBTWBuildChallenge#21]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: 
  Techsters
- Challenge Contact Person Name: 
  Ujala Bharti
  Abhishek Dey
- Campus Name: 
  SRM RAMAPURAM
  ### Idea Description

We are all worried about our privacy, we upload our private contents(valuable information) into our social media profiles and we do it everyday and sometimes these information are stolen and presented in an explicit manner. So the basic idea to to develop a tool that will allow people to report privacy related issues on the internet, supposing There are two people, One is Samantha and other is her mate Jack, So Jack while surfing the internet finds Samantha's pic and other contents uploaded and being used as a fake profile, i.e identity theft, Jack can report it if its on the social media(Facebook, Twitter, etc) but he cannot do much(Because he might be a layman) and (if he knows a bit about privacy) if its somewhere else on the internet like a personal blog with no admin information(Anonymous websites, blog, portals, search engines), So This  Tool Basically Will help Jack report the link which will be viewed by a panel of investigators who will investigate the matter by following certain guidelines as provided by the application and if the content is really stolen, the author impersonating Samantha will be sent a mail by automated systems regarding the matter, and still if the author of the content doesn't removes the content, Jack will be provided with guidelines what to do next..
Like 
Reporting it to Cyber Crime, 
Procedures of reporting it to cyber cell,
Nearest Cyber crime cells

Furthermore we will try to integrate Functionalities Like Content Retrieval and automated checking for matches..in audio, files, etc too.

_Please answer all of the questions below._
- Idea name:
  Privme
- What is the problem you are solving for:
  Content Duplication, Identity Theft
- Who encounters that problem (who is your audience - describe them): 
  Common People(Layman)
- How will your tool solve this problem for these people:  

People will have a hope to take action against content theft.
- What are you going to create (app, add-on, extension, etc.): 
  App, Maybe Extension
- What are the next steps for building this tool: 
1. Planning The modules,
2. Programming
3. Testing The Tool
4. Debugging(If there are any bugs)
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @ScottDowne @jeffbryner

**Comment by jeffbryner** [comment]
@thegtagamer Sounds interesting! What target 'Nearest Cyber crime cells' did you have in mind?

**Comment by thegtagamer** [comment]
Cops have a cyber crime unit..And..most of the people don't know how to proceed with that..so the goal here is to provide them the guidelines on the basis of their country so they can know how they can report these activities @jeffbryner

**Comment by ScottDowne** [comment]
Should there be a step where Samantha can be informed before this is sent out?

I also worry about the "panel of investigators" and wonder if it should go directly to proper authorities after Samantha has been notified? I guess I'm a bit worried that the privacy matter is not being handled as discreetly as it could or with proper credibility. Either way, I think this is an area that you'll need to be very careful handling.

**Comment by thegtagamer** [comment]
@ScottDowne Sure there should be a step, thanks for the advice Scott, I totally forgot it.
And yes about the discretion, Whatever happens stays in between Jack, Samantha and the system and their details are not being revealed to the outside world, Yes this area does needs very careful handling.

**Comment by charissalaisy** [comment]
@thegtagamer, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @thegtagamer! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
