### ISSUE TITLE
Beginner Friendly Internet

### ISSUE THREAD

**Issue by Hasilt** [mozilla/TBTWBuildChallenge#22]
Team Name: **Prudence**
- Challenge Contact Person Name: Hasil t
- Campus Name: CUCEK
### Idea Description

_Please answer all of the questions below._
- Idea name: Beginner Friendly Internet
- What is the problem you are solving for: It is a difficult task to install all those privacy addons and stuff after you install your browser for the first time on a new pc or fresh Operating System. So we are trying to make this task simple as possible.
  And also for Internet beginners it may take some time to know all about all those privacy issues and take counter measures against them. We would like to make them first install counter measures and then learn about privacy.
- Who encounters that problem (who is your audience - describe them):  Most of us encountered this problem once in a while. I usually have this problem when I reinstall my operating system. And also heard my little cousin saw inappropriate ads on his browser window when he started to use his first computer.
- How will your tool solve this problem for these people:  Our tool will automatically install all privacy measures at once it executed.
- What are you going to create (app, add-on, extension, etc.): Shell script
- What are the next steps for building this tool: Integrate this tool along with the browser.
- Links to additional information: none

**Comment by LucyeoH-zz** [comment]
Reviewers: @ScottDowne @jeffbryner

**Comment by jeffbryner** [comment]
Nice idea. There may be intersection here to this work by @atcuno https://gist.github.com/atcuno/3425484ac5cce5298932 But an automated way of 'just doing it' would be really great!

**Comment by ScottDowne** [comment]
Yeah I'm with Jeff on an automated way of 'just do it' but in general it's a good idea and a good first step.

**Comment by charissalaisy** [comment]
@Hasilt, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @Hasilt! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.

**Comment by Hasilt** [comment]
Thanks for your feedback. We will come up with a prototype as soon as possible.
