### ISSUE TITLE
Body temprature/heart rate monitoring band for elders and infants

### ISSUE THREAD

**Issue by sourabhtk37** [mozilla/TBTWBuildChallenge#23]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Cookie Destroyers
- Challenge Contact Person Name:T K Sourabh 
- Campus Name: Bhagwan Parshuram Institute Of technology
### Idea Description

_Please answer all of the questions below._
- Idea name:Cheap heart rate/body temprature monitoring device for elders and infants
- What is the problem you are solving for:1.Usually people are not constantly around their elders and when their health deteriorate they may not be able to call for help.The same is the case for infants,poor people may not afford keeping their infants in incubator so,we need to monitor the infants body temprature.
- Who encounters that problem (who is your audience - describe them): 
  The audience is usually poor people and people with elders who are not around them most of the time
- How will your tool solve this problem for these people:  
  By creating a small and cost-effective band that monitors heart beat and body temprature
- What are you going to create (app, add-on, extension, etc.): 
  We will create a app for the adult version, to send a distress signal to the phone when the band sends a emergency sos signal
- What are the next steps for building this tool: 
  We need to implement IOT within this device for the adult version.
- Links to additional information: 
  I have to research more on this project but i don't have enough confidence to move this Idea.I with my team presented this Idea at an event in my freshman year

**Comment by LucyeoH-zz** [comment]
Reviewers: @ScottDowne @jeffbryner

**Comment by jeffbryner** [comment]
Love the team name. 

It's not clear whether the band exists already and you are focusing on the app or whether this is to build the band?

**Comment by sourabhtk37** [comment]
if the band exist then I would concentrate on building the app. @jeffbryner

**Comment by ScottDowne** [comment]
Sounds like it could help a lot of people.

It's cheap, so it would need a high demand and distribution, or something like government backing which would care less about profits and more about getting it to the people that need it.

It's not clear how it deals with data, and I believe that's the goal of this. However, I do see how doing something like this cheap and with data privacy as a concern is connected, I just didn't see anything about data privacy in the proposal.

**Comment by sourabhtk37** [comment]
Exactly what my concern was this is not related to data privacy,which I totally forgot about while submitting. That's stupid of me. I am sorry

**Comment by charissalaisy** [comment]
@sourabhtk37, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @sourabhtk37! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.

**Comment by sourabhtk37** [comment]
Hey, Closing this Issue as it's not needed anymore.
