### ISSUE TITLE
Image crawling tracker

### ISSUE THREAD

**Issue by SubhrajyotiSen** [mozilla/TBTWBuildChallenge#24]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: MVIT Privacy Crew
- Challenge Contact Person Name: Subhrajyoti Sen
- Campus Name: Sir M. Visvesvaraya Institute of Technology
### Idea Description

_Please answer all of the questions below._
- Idea name: Image Crawling tracker
- What is the problem you are solving for: An image uploaded on one website (particularly a social networking website) being shown/available on other websites at all. The privacy concern comes in especially when personal pictures are shared
- Who encounters that problem (who is your audience - describe them): Anyone using Social Networking websites
- How will your tool solve this problem for these people:  It will alert the users of the possible list of websites the image might be available on while the image is being uploaded.
- What are you going to create (app, add-on, extension, etc.): add-on
- What are the next steps for building this tool: designing an algorithm to find the list of websites that crawl a particular website
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @jeffbryner @mikeconley

**Comment by jeffbryner** [comment]
Is this looking for particular images ala a reverse image search? 
https://inteltechniques.com/OSINT/reverse.image.html

**Comment by SubhrajyotiSen** [comment]
No. We are aiming to list various possible places on the internet where an image that you are currently uploading might be available/visible in the future

**Comment by mikeconley** [comment]
Hey MVIT Privacy Crew,

I like the idea of giving users more knowledge about what can happen to their personal photographs.

If I'm understanding correctly, what you're proposing is a tool that learns over time where photos uploaded to a particular site tend to end up?

I'm concerned, however, that the answer to the question "where can my photo end up if I upload it here" is "everywhere". Suppose I upload a photo of myself and my nephew to Facebook. Nothing is stopping one of my Facebook Friends from copying that photo, and uploading it to Flickr, which can then get passed along to some Diaspora\* server, or perhaps is uploaded to a Stock Photo site, or perhaps is just hosted on someone's personal blog. I don't think image appropriation like this is a straight line from one site to another - I think it hops around and proliferates all over the place.

Am I misunderstanding your proposal? If so, can you please help me understand? And if not, how do you plan on addressing the above issue?

**Comment by SubhrajyotiSen** [comment]
Hey,
you have understood our idea properly. Unfortunately we hadn't thought about the issue which you mentioned. Our team is brainstorming on it right now

**Comment by charissalaisy** [comment]
@SubhrajyotiSen, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @SubhrajyotiSen! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
