### ISSUE TITLE
Track-Path

### ISSUE THREAD

**Issue by salmanfarisvp** [mozilla/TBTWBuildChallenge#25]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: KickC
- Challenge Contact Person Name: Salman Faris
- Campus Name: Jamia Nadwiya Arts And Science College
### Idea Description

_Please answer all of the questions below._
- Idea name:Track-Path
- What is the problem you are solving for:to show how our online activities are tracking the gaints like google and facebook
- Who encounters that problem (who is your audience - describe them):  the normal internet users
- How will your tool solve this problem for these people:  that will show to how they track on us , if we find the way we can solve that, like location tracking we prevent using to off our location .like that
- What are you going to create (app, add-on, extension, etc.): An extension because in the case thet will be more suitable. if open a web site and activate the add-on then we know where the tracking is goes like that. where the site sharing our data's
- What are the next steps for building this tool: we want to know more about the hunting the track' , we have to track the trakers
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @jeffbryner @mikeconley

**Comment by jeffbryner** [comment]
How is this different than the existing tracker identifiers like ghostery, lightbeam etc?

**Comment by mikeconley** [comment]
Hey KickC,

Along with @jeffbryner 's question, can you also go into more detail about _how_ you plan on detecting tracking behaviors (for example, the location tracking you brought up)?

**Comment by charissalaisy** [comment]
@salmanfarisvp, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by salmanfarisvp** [comment]
Thanks Ma'am, sure

**Comment by charissalaisy** [comment]
Hey @salmanfarisvp! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
