### ISSUE TITLE
   The Pirates of Privacy

### ISSUE THREAD

**Issue by vimoxshah** [mozilla/TBTWBuildChallenge#26]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: 
  The Pirates of Privacy
- Challenge Contact Person Name: Vimox Shah
- Campus Name: Privacy of Anonymous
### Idea Description

_Please answer all of the questions below._
- Idea name: Not decided yet
- What is the problem you are solving for: Teach other people how to analyze web and app how to diifferentiate them
- Who encounters that problem (who is your audience - describe them): 
  Students of Engineering College
- How will your tool solve this problem for these people:  
- What are you going to create (app, add-on, extension, etc.): App
- What are the next steps for building this tool: first complete design phase 
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @jeffbryner @mikeconley

**Comment by mikeconley** [comment]
Hello Pirates of Privacy,

This submission is really lacking in detail. Can you elaborate a bit more about what you'll be teaching people, how you'll be teaching them, and how it aligns with the security and privacy theme of this Take back the Web Challenge?

**Comment by charissalaisy** [comment]
@vimoxshah, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @vimoxshah! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
