### ISSUE TITLE
OHOME

### ISSUE THREAD

**Issue by diomabb** [mozilla/TBTWBuildChallenge#28]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Genius team privacy soldiers
- Challenge Contact Person Name:Abbackar Diomande 
- Campus Name: Centre de Recherche et d'Action pour la Paix
### Idea Description

_Please answer all of the questions below._
- Idea name: OHOME
- What is the problem you are solving for:
  Crisis and high cost of housing for many years in several African countries
  Absence of economic housing and cities for students in Africa.
  rental problem for African students
  Absence of roomate solution for african students
- Who encounters that problem (who is your audience - describe them):My main target is the set of students in my country and in Africa lack of resources does not pouvants suitable housing.... 
- How will your tool solve this problem for these people:  
- What are you going to create (app, add-on, extension, etc.): OHOME is a web platform and mobile application, facilitating the linking of student
    Ivorian universities eager to share accommodation.
  The contenders roommates can view other user profiles who seek or offer a roommate.
  OHOME help
  student groups to form one purpose that of cohabitation.
  Will assist and facilitate the linking of these student groups with structures
  Internet is a place of meeting and sharing, so we thought it would be nice to use
  as a support to enable all these young people to meet in order to live together.
  OHOME is a free platform and wants to be very dynamic and ambitious.
- What are the next steps for building this tool: Redaction of the tender specifications
  design of the model
- Links to additional information: 
  http://www.cotoiturage.fr/

**Comment by LucyeoH-zz** [comment]
Reviewers: @jeffbryner @mikeconley

**Comment by mikeconley** [comment]
Hello Genius team privacy soldiers (I love that name),

Thanks for your submission. According to [the Take Back the Web Build Challenge website](https://takebacktheweb.mozilla.community/role/build-technology/), the goal is to: "design a prototype of a powerful tool that will help people understand why privacy and security is important. It can be an app, an add-on, extension, plugin, website or anything that helps people be more aware of their privacy & security online."

I'm not exactly sure how OHOME fits those criteria. Can you elaborate a bit more on how your project increases awareness and empowers users in the security and privacy problem space?

**Comment by charissalaisy** [comment]
@diomabb, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @diomabb! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
