### ISSUE TITLE
Build Technology Idea Submission [Facebook Spy 007]

### ISSUE THREAD

**Issue by rjrajivjha** [mozilla/TBTWBuildChallenge#3]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name:  Wings of fire, USICT, New Delhi, India
- Challenge Contact Person Name: Rajiv Kumar Jha
- Campus Name: University School of information and communication technology
### Idea Description

_Please answer all of the questions below._
- Idea name: [Facebook Spy 007]
- What is the problem you are solving for: Loads of Fake Ids, which are threat to personal space of one's life. They are registered on daily basis & have also led to many cyber crimes & increased psychological issues. 
- Who encounters that problem (who is your audience - describe them): Facebook users
- How will your tool solve this problem for these people:  We would build an add-on under which a receiver would upvote a registered fb id as fake or trustworthy when a request is being sent by a user.
  With the help of these upvotes , people will be able to get a general idea of the users available online. Depending upon the result of this add-on,  a request o fb can  be made which will report the id.
- What are you going to create (app, add-on, extension, etc.):  An add-on
- What are the next steps for building this tool: We will frame our algorithm, and then script it. We will also test the beta-version of add-on many a times with in our campus to have a general survey, before finally proposing our add-on with the documentation.
- Links to additional information: none.

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @brianking

**Comment by abbycabs** [comment]
Thanks for the idea @rajivjhaimin! Would it be easier to determine the trustworthiness of a facebook account based on things like: # of friends (do you have any mutual friends), do they have a profile pic, have they uploaded anything? Gathering enough information in your crowd-sourced database may take awhile / may not provide enough value to the user evaluating whether or not they are trustworthy.

**Comment by brianking** [comment]
I like the idea in general, but am wondering if creating white/black lists is the most effective method of doing this. For example, I can imagine it being abused and an effort by some to blacklist legitimate users.

After some cursory research, it seems FB doesn't provide resources of their own for this beyond reporting potential fake accounts and cleaning up fake users as it encounters them.

A good start might be something like the following:
- create a list of characteristics of fake accounts, and make them available publicly.
- Create another opt-in layer. Pop up an alert when somebody accepts a friend request, asking them if they have double checked and are sure they know this person.

**Comment by charissalaisy** [comment]
@rajivjhaimin, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll consider using the feedback you got to go on to the next phase by turning this into a prototype. 

A prototype can come in many different forms, some of which you can read about here: https://hackdesign.org/lessons/10.

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!
