### ISSUE TITLE
Submit my idea 

### ISSUE THREAD

**Issue by fayazkhan121** [mozilla/TBTWBuildChallenge#31]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Firefox.aup
- Challenge Contact Person Name: Fayaz Khan
- Campus Name: Abasyn university Peshawar
### Idea Description

_Please answer all of the questions below._
- Idea name:Secure your data
- What is the problem you are solving for:
  secure user data from third parties
- Who encounters that problem (who is your audience - describe them): 
  Me and my team
- How will your tool solve this problem for these people:  
  my tool is solve this problem for people when we search some thing so it make more secure our data
- What are you going to create (app, add-on, extension, etc.): 
  extension
- What are the next steps for building this tool: 
  first of all with my team build these type of tool and then think about to make a app to
- Links to additional information: 

no link yet

**Comment by LucyeoH-zz** [comment]
Reviewers: @jeffbryner @mikeconley

**Comment by mikeconley** [comment]
Hey Firefox.aup,

Your submission is missing a lot of key information and detail. I understand that you want to secure user data. Can you go into more detail about which user data you're securing, and how?

**Comment by charissalaisy** [comment]
@malikfayaz1, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @malikfayaz1! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
