### ISSUE TITLE
Privacy::ReadMe

### ISSUE THREAD

**Issue by vipinkhushu** [mozilla/TBTWBuildChallenge#32]
# Build Technology Idea Submission
- Team Name: WebKnights
- Challenge Contact Person Name: Vipin Khushu
- Campus Name: YMCA University Of Science And Technology, Faridabad
### Idea Description
- Idea name: Privacy Statement | Read Me
- What is the problem you are solving for: Whenever submitting a form on a website, we are provided with privacy statement and terms and conditions to read, in which it is clearly written how the respective website will handle our data and how private our data will be kept but people just skip reading it and just submit the form.
- Who encounters that problem (who is your audience - describe them): Every internet user encounters this problem. 
- How will your tool solve this problem for these people:  

Our tool will solve this problem in following ways:-
1. Check whether the form is proving privacy statements.
2. Whether the user has completely read the privacy statement.
- What are you going to create (app, add-on, extension, etc.): 
  This will be a javascript code.
- What are the next steps for building this tool: 
  Our team is proficient in working with web technologies, We will use our knowledge and start coding this as soon as our idea gets approved.
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @jeffbryner @mikeconley

**Comment by mikeconley** [comment]
Hey WebKnights,

I think this is a very cool idea. I agree that Terms of Service and Privacy Policies are nearly always opaque walls of text for the user, and they have no idea what they're agreeing to (and I think it's also kinda questionable how enforceable the agreement is).

Some previous work in this space is by Terms of Service; Didn't Read: [https://tosdr.org](https://tosdr.org). There's an API you might be able to make use of there.

I'm also interested in what you mean by "whether the form is proving privacy statements". Can you elaborate on what you mean by that? How will you test for it?

"Knowing whether the user has completely read the privacy statement" is probably something that the issuer of the ToS cares about. My suggestion is to empower the user more, and rephrase - "Knowing whether the user has completely understood the privacy statement".

[Legalsifter](https://www.legalsifter.com/) is also worth looking at for inspiration. They're using natural language processing and machine learning to consume legal documents and generate reports. Perhaps that's a route you could explore as well.

**Comment by charissalaisy** [comment]
@vipinkhushu, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @vipinkhushu! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
