### ISSUE TITLE
Projects for every1

### ISSUE THREAD

**Issue by Aakash3476** [mozilla/TBTWBuildChallenge#33]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name:  Qpage
- Challenge Contact Person Name: Aakash Panchal
- Campus Name: GTU PG SCHOOL
### Idea Description

_Please answer all of the questions below._
- Idea name: Projects for all
- What is the problem you are solving for: The problem with students is that they cannot find their right choice of project which suite their caliber. 
- Who encounters that problem (who is your audience - describe them): All the bacholer and master student require this.
- How will your tool solve this problem for these people:  They get all the material under a single platform.
- What are you going to create (app, add-on, extension, etc.): mobile and web app
- What are the next steps for building this tool: 
- Links to additional information: https://www.youtube.com/watch?v=gvXUmza6rZs

**Comment by LucyeoH-zz** [comment]
Reviewers: @mikeconley @wagnerand

**Comment by mikeconley** [comment]
Hello Qpage,

Thanks for your submission. According to [the Take Back the Web Build Challenge website](https://takebacktheweb.mozilla.community/role/build-technology/), the goal is to: "design a prototype of a powerful tool that will help people understand why privacy and security is important. It can be an app, an add-on, extension, plugin, website or anything that helps people be more aware of their privacy & security online."

I'm not exactly sure how Projects for all fits those criteria. Can you elaborate a bit more on how your project increases awareness and empowers users in the security and privacy problem space?

**Comment by charissalaisy** [comment]
@Aakash3476, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @Aakash3476! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
