### ISSUE TITLE
web security

### ISSUE THREAD

**Issue by arupmohanty18** [mozilla/TBTWBuildChallenge#34]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: CYBER KINGS 
- Challenge Contact Person Name: Arup Mohanty;Shakya Swasti Mohanty
- Campus Name: Institute of Technical Education and Research
### Idea Description

_Please answer all of the questions below._
- Idea name:Web Security
- What is the problem you are solving for:to save the web apps from any kind of cyber attack
- Who encounters that problem (who is your audience - describe them): the local users who use the net regularly
- How will your tool solve this problem for these people: 
- What are you going to create (app, add-on, extension, etc.): app
- What are the next steps for building this tool: we will work upon it first
- Links to additional information: 
  my mail id arupmohanty18@gmail.com, Here you can provide any information you want to share.

**Comment by arupmohanty18** [comment]
Web application security is a branch of Information Security that deals specifically with security of websites, web applications and web services. At a high level, Web application security draws on the principles of application security but applies them specifically to Internet and Web systems.

**Comment by LucyeoH-zz** [comment]
Reviewers: @mikeconley @wagnerand

**Comment by mikeconley** [comment]
Hello Cyber Kings,

I think your pitch needs a bit of expansion and detail. Protecting web applications from a malicious user is an interesting goal, but the most important part of your pitch is missing: "How will your tool solve this problem for these people".

Can you please elaborate on that point a bit? Specifically, what will your app do, and how will it do it?

**Comment by charissalaisy** [comment]
@arupmohanty18, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @arupmohanty18! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
