### ISSUE TITLE
The Eye Of Future

### ISSUE THREAD

**Issue by sooraj111** [mozilla/TBTWBuildChallenge#35]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Private Assassins
- Challenge Contact Person Name: Sooraj Kumar 
- Campus Name: DHA Suffa University
### Idea Description

_Please answer all of the questions below._
- Idea name: The Eye of Future
- What is the problem you are solving for: People often have trouble unlocking their devices with their hands. 
- Who encounters that problem (who is your audience - describe them): Me, my buddies and half of the population of this world.
- How will your tool solve this problem for these people:  By Scanning there eyes.
- What are you going to create (app, add-on, extension, etc.): Physical Tech. (Eye Scanner)
- What are the next steps for building this tool: Team, Financial Support.
- Links to additional information: (N/A)

**Comment by LucyeoH-zz** [comment]
Reviewers: @mikeconley @wagnerand

**Comment by mikeconley** [comment]
Hello Private Assassins!

[According to the Take Back the Web Build Challenge site](https://takebacktheweb.mozilla.community/role/build-technology/), your task is to "design a prototype of a powerful tool that will help people understand why privacy and security is important. It can be an app, an add-on, extension, plugin, website or anything that helps people be more aware of their privacy & security online."

I'm uncertain how your pitch helps people become more aware of their privacy and security. I understand that it's a mechanism to unlock their device, which falls under security, but how do you envision it increasing awareness?

I'm also interested in the eye scanner technology you're planning on building. Are you planning on finding a way of scanning the retina? Or are you scanning the iris? Or something else entirely? Are you going to use the technology already built into many phones (front-facing camera), or are you planning on having a peripheral of some kind?

**Comment by charissalaisy** [comment]
@sooraj111, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @sooraj111! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
