### ISSUE TITLE
Build the Technology Challenge[ Facebook Image Seeker]

### ISSUE THREAD

**Issue by rjrajivjha** [mozilla/TBTWBuildChallenge#4]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Wings of fire, USICT, New Delhi, India
- Challenge Contact Person Name: Rajiv Kumar Jha
- Campus Name: University School Of Information and Communication Technology
### Idea Description

_Please answer all of the questions below._
- Idea name: Facebook Image Seeker
- What is the problem you are solving for: Facebook Image Morphing. People morph or misuse the image of others to take the revenge which leads to mental harassment .This idea can serve as extension of issue #3 .
- Who encounters that problem (who is your audience - describe them):  Facebook Users (Mostly women.)
- How will your tool solve this problem for these people:   It will tell the facebook users, whether anyone else is using their image, If they are not in the friend list of the user. With the help of this they will get notification each time they will activate this add-on on their facebook page.
- What are you going to create (app, add-on, extension, etc.): An add-on or app
- What are the next steps for building this tool: I will design Algorithm.
- Links to additional information: None.

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @brianking

**Comment by abbycabs** [comment]
@rajivjhaimin this is an interesting idea that would have real world impact! I have a couple questions around feasibility: While you might be able to detect photos of a certain user through facial recognition, how are you scanning photos uploaded by those who are not friends of the user? You likely won't have access to that photo. Or are you scanning every public photo uploaded to facebook?

**Comment by brianking** [comment]
I have the same feasibility questions as @rajivjhaimin. 

I would also ask about what happens if they do successfully find misused images? What next?

**Comment by charissalaisy** [comment]
@rajivjhaimin, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll consider using the feedback you got to go on to the next phase by turning this into a prototype. 

A prototype can come in many different forms, some of which you can read about here: https://hackdesign.org/lessons/10.

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!
