### ISSUE TITLE
Do Not Track

### ISSUE THREAD

**Issue by karanbehl** [mozilla/TBTWBuildChallenge#42]
# Build Technology Idea Submission
- Team Name: The privacy Group
- Challenge Contact Person Name: Karan Behl
- Campus Name: CT Institute of Engineering Management and Technology
### Idea Description
- Idea name: Do Not Track
- What is the problem you are solving for: It will check whether the site is placing 3rd party cookies and whether the your browser protect for fingerprinting or not.
- Who encounters that problem (who is your audience - describe them): Internet Users
- How will your tool solve this problem for these people:  Extension will warn the users about the websites placing 3rd party cookies and will also warn whether the browser is protecting from fingerprinting or not. Possibly we will provide suggestions to users to secure their privacy. 
- What are you going to create (app, add-on, extension, etc.): Extension
- What are the next steps for building this tool: Gathering Information about fingerprinting and cookies and how to stop it.
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @wagnerand  @k88hudson

**Comment by wagnerand** [comment]
Hi privacy group,

thank you for your submission.

I have a couple of questions:
- While it's certainly true that a lot of third-party cookies are used for tracking, some others are essential for the website to work. How would identify and distinguish third-party cookies needed for the website to work from ones that don't? Warning about all third-party cookies could lead users into breaking those websites if they decide to block them.
- How exactly are you going to do fingerprinting protection? There are a lot of different techniques to do fingerprinting, some quite obscure.

**Comment by charissalaisy** [comment]
@karanbehl, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @karanbehl! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
