### ISSUE TITLE
encrypt

### ISSUE THREAD

**Issue by ritwizme** [mozilla/TBTWBuildChallenge#43]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: 
  Bounty Hunters
- Challenge Contact Person Name: Ashwin Rana
- Campus Name: SRM University, ramapuram
### Idea Description

_Please answer all of the questions below._
- Idea name:Encrypt
- What is the problem you are solving for: Data privacy 
- Who encounters that problem (who is your audience - describe them): everyone who is connected through public wifi hotspots.
- How will your tool solve this problem for these people:  by encrypting the data which is being passed on over the server automatically and providing key for decryption to the trusted service provider.
- What are you going to create (app, add-on, extension, etc.):  an app.
- What are the next steps for building this tool: working on the prototype and filling all the loop-holes to come up with a proper app for public use and data safety. 
- Links to additional information: http://www.welivesecurity.com/2014/11/14/public-wi-fi-hotspots-know-risks/,http://www.howtogeek.com/178696/why-using-a-public-wi-fi-network-can-be-dangerous-even-when-accessing-encrypted-websites/

**Comment by LucyeoH-zz** [comment]
Reviewers: @wagnerand  @k88hudson

**Comment by wagnerand** [comment]
Hi Bounty Hunters,

thank you for your submission.

I have a couple of questions:
- Who would be a trusted service provider? A website owner? An ISP? A third party?
- How is this different from HTTPS?
- If you want to encrypt the whole traffic, how is this different from traditional VPN services?
- Some data cannot be encrypted like URLs using the current protocols. Are you going to design a new internet protocol?

**Comment by charissalaisy** [comment]
@ritwizme, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @ritwizme! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
