### ISSUE TITLE
ADEBAYO NATHANIEL - PRESTIGE TEAM

### ISSUE THREAD

**Issue by prestigeteam** [mozilla/TBTWBuildChallenge#44]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: PRESTIGE TEAM
- Challenge Contact Person Name: ADEBAYO NATHANIEL
- Campus Name: FEDERAL UNIVERSITY OF TECHNOLOGY, MINNA
### Idea Description

_Please answer all of the questions below._
- Idea name: GET IT RIGHT
- What is the problem you are solving for: ILLITERACY OF THE PRIVACY AND SECURITY IN WEB
- Who encounters that problem (who is your audience - describe them): CAMPUS STUDENTS
- How will your tool solve this problem for these people:  THEY WILL BE ENLIGHTENED ABOUT THE PRIVACY SETTINGS. 
- What are you going to create (app, add-on, extension, etc.): 
  AN ADD - THIS ADD WILL BE AUTOMATICALLY CONNECTED TO EXTENSION WHERE IT SHOWS ON THE SCREEN OF USERS IN WWW TELLING THEM AND GIVING THEM FEW INFRMATIONS ON NETWORK PRIVACY
- What are the next steps for building this tool: 
  WORDY FOR THE ADDS
  BUILDING
  IMPLEMENTATION
  TESTING
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @wagnerand @k88hudson

**Comment by wagnerand** [comment]
Hi prestige team,

thank you for your submission.

Can you please elaborate what exactly your idea is? What do you mean by "add"? Which extension will it connect to? What information will you provide to users and how will they help educating about security and privacy?

**Comment by charissalaisy** [comment]
@prestigeteam, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @prestigeteam! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
