### ISSUE TITLE
Text Mining 

### ISSUE THREAD

**Issue by Raamthinker** [mozilla/TBTWBuildChallenge#45]
[Idea MF.txt](https://github.com/mozilla/TBTWBuildChallenge/files/263416/Idea.MF.txt)
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Tecroids
- Challenge Contact Person Name:  K.P.Balavasu,K.Ramachandran
  [Idea MF.txt](https://github.com/mozilla/TBTWBuildChallenge/files/263415/Idea.MF.txt)
- Campus Name: KLN college of Engg
### Idea Description

_Please answer all of the questions below._
- Idea name:
  Text mining
- What is the problem you are solving for: 
  wide range of text to align to its particular category
- Who encounters that problem (who is your audience - describe them): 
  Now a days social media etc... to be used many text data so that to rectify particular category of text to be mentioned & low data missing
- How will your tool solve this problem for these people:  To be use many areas of data texting to solve unlimited text mining
- What are you going to create (app, add-on, extension, etc.): 
  web tool (php)
- What are the next steps for building this tool: asp.net,css,html
- Links to additional information: 
  I particulary use this concept to control the unlimited data of text mining and the  minise the SERVER work and without any lag of texting to be controlled

**Comment by LucyeoH-zz** [comment]
Reviewers: @wagnerand  @k88hudson

**Comment by wagnerand** [comment]
Hi Tecroids team,

thank you for your contribution.

I am not sure how your idea is submitted to the topic which is making "people more aware of their privacy and security online". Can you please elaborate?

**Comment by charissalaisy** [comment]
@Raamthinker, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @Raamthinker! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.

**Comment by Raamthinker** [comment]
Thanks for your Suggestions...
