### ISSUE TITLE
VR application for security awarness

### ISSUE THREAD

**Issue by GeekyShiva** [mozilla/TBTWBuildChallenge#46]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Open Source Nomads
- Challenge Contact Person Name: Shivang Shekhar
- Campus Name: NIIT University
### Idea Description

_Please answer all of the questions below._
- Idea name:VR for Security
- What is the problem you are solving for:giving a new definition for learning in the field of security via virtual reality.
- Who encounters that problem (who is your audience - describe them): Any student/developer who is bored of reading and wants to learn in a new exciting way for a better understanding.
- How will your tool solve this problem for these people:  Giving them the learning application they never had.
- What are you going to create (app, add-on, extension, etc.): app.
- What are the next steps for building this tool: Creating High quality VR content using Mozilla's own MozVR and aframes.
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @wagnerand  @k88hudson

**Comment by wagnerand** [comment]
Adding @bacharakis. Maybe someone with a VR background could have a look at this? Thanks!

**Comment by bacharakis** [comment]
Thanks @wagnerand ! I happen to have some experience on MozVR and A-frame.

@GeekyShiva I love your idea! It's fresh, different and unique!
Can you please share some more information regarding the content of the app? What this app will do exactly?

Looking forward for your feedback!

**Comment by GeekyShiva** [comment]
Hi @bacharakis ,glad to see your interest in my application

Basically what I want is an application or a website or an extension (whichever is more feasible and can reach out more users ,I will need to help of Mozilla analysis of these sectors to select the platform),I want to deliver high quality VR content that will help people and developers understand the concept of privacy and network security all through VR, I wish to design WebVR content using aframes for the developers  and students can view and learn from it regarding privacy ...it will be and interactive VR application. All ways and threats will be depicted in an immersive way by taking users into the network via VR and giving them information regarding all possible threats and security measures.

**Comment by GeekyShiva** [comment]
Ask for as much details you need ....happy to provide :+1: :)

**Comment by bacharakis** [comment]
Thanks @GeekyShiva !

Can you give me an example of the applications content that you would like to present through your VR app?

**Comment by charissalaisy** [comment]
@GeekyShiva thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @GeekyShiva! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.

**Comment by GeekyShiva** [comment]
@bacharakis Hi,
An example can be of this kind 
View these links ,these links don't contain the exact type of content i am discussing here but relates to most of the content we will provide in the application- https://www.youtube.com/watch?v=XonlDNlJdXc
https://www.youtube.com/watch?v=CekHRTMxEmY
https://www.youtube.com/watch?v=d4XZwSxeUIw
http://vrse.com/

Imagine Facebook CTF on Virtual reality ,we can very well imagine the immersive experience that can be given in teaching and development via VR .

Knowing the networks ,security systems and using a virtual tutor to teach what content we have on MDN or sections of MDN . Imagine TBTW can be completely virtual all our material for learning and resources go virtual and i can easily prototype things of my interest virtually with the help of a tutor.
That is the content i am going to give on this platform.

The level of Interest that we can grow in people towards learning the web technologies is great .

This will change the way of sharing of knowledge in open source world.
