### ISSUE TITLE
* Team name : Moz HETEC

### ISSUE THREAD

**Issue by codecaiine** [mozilla/TBTWBuildChallenge#47]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name:  Mozhetec
- Challenge Contact Person Name: Saint Cyr
- Campus Name: HETEC Abidjan
### Idea Description

_Please answer all of the questions below._
- **Idea name**: HelpRS
- *_**What is the problem you are solving for__:_\* 
  The social network account hacking and data stealing.
  .
- Who encounters that problem (who is your audience - describe them): 
  In Ivory Coast , Facebook is the social network most used by Ivorian but also one of the most used by crook and hackers. Through impersonation , the links shipments with computer viruses to hack the accounts of users of social networks.
- **How will your tool solve this problem for these people**:  
  Identify different methods of password hacking , scams on social networks , especially Facebook . And educate users in how to protect themselves , or how to behave in case of hacking , all the good tips 
- What are you going to create (app, add-on, extension, etc.): 
  App 

**\* **What are the next steps for building this tool**:*\* 
Identify the methods of hacking and stealing data on social networks especially Facebook and solutions.
Skip to prototype
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @wagnerand @k88hudson

**Comment by wagnerand** [comment]
Hi  Mozhetec team,

thank you for your submission.

I have a couple of questions:
- Do you already have data about the different methods of identity stealing? If not, how would you gather them? How do pick solutions for the gathered methods?
- What will your app do exactly?
- How would users know about the app? Would it interact with Facebook directly? How does the app protect users?

**Comment by charissalaisy** [comment]
@NYBA90, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @NYBA90! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
