### ISSUE TITLE
MozTBW ideas awareness website has The African

### ISSUE THREAD

**Issue by CoolZie** [mozilla/TBTWBuildChallenge#48]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: mozpigierclub
- Challenge Contact Person Name: 
- Campus Name: piger cote d'ivoire
### Idea Description

_Please answer all of the questions below._
- Idea name: 
  website humor awareness videos
- What is the problem you are solving for:
  the problems is that people do not go to the information, they prefer things unimportant to them or the data protection is very important to them and that the fight is noble mozilla
- Who encounters that problem (who is your audience - describe them): 

almost everyone who is not in the information field that do not have Internet notions .they use the internet but do not know how to do how to protect
- How will your tool solve this problem for these people:  

the tool will solve the problem because it will be accessible and clear view that the idea made ​​in the video are set on a site of increasingly large company notament in Africa uses humor to sell their product is the same idea right here
- What are you going to create (app, add-on, extension, etc.): 

awareness video website
- What are the next steps for building this tool: 

the next step is the development and implementation of the site and to advertise to make known the idea to raise more person
- Links to additional information: 
  none link

**Comment by LucyeoH-zz** [comment]
Reviewers: @wagnerand  @k88hudson

**Comment by CoolZie** [comment]
ok thanks

**Comment by wagnerand** [comment]
Hi mozpigierclub,

thank you for your contribution.

How are you going to make users aware of the video and make sure they watch and understand it? How would you handle upcoming questions?
Can you please elaborate how your idea will solve the problem and how it's different from other educative and funny ("infotainment") videos that already exist?

**Comment by CoolZie** [comment]
hi it is clear that there is already the educative videos and both funny that we're talking about is one that everyone should look indeed deserves his fight our cause you have paused the question of how to raise awareness?
our communication technique focuses on the proximity of our listeners we want and we will go to them so they know the importance of their data. the idea is the massive e sharing our videos on social networks and sharing links in our email and sms discussing on the net every Monday we animate our computer club of small IT courses for non-IT and Wednesday pure IT courses for IT professionals to its meetings we will pass the information awareness watch all the videos and tell them protection practice ask them to talk about them and can be so mozilla gives us the opportunity posting her videos their information site with our local coatch Manuella kouadio we are working on it own way to go about it

Sincerely thank you mozpigierclub

**Comment by wagnerand** [comment]
Your comment is very hard to read. Can you please edit it, add some punctuations and form proper sentences? Thank you.

**Comment by CoolZie** [comment]
i uses google traduction i speak french sorry

**Comment by charissalaisy** [comment]
Hey @CoolZie! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
