### ISSUE TITLE
Build Technology Idea Submission

### ISSUE THREAD

**Issue by dbms** [mozilla/TBTWBuildChallenge#49]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Wings of fire, USICT, New Delhi, India.
- Challenge Contact Person Name: Rajiv Kumar Jha
- Campus Name: University School of Information and Communication Technology.
### Idea Description

_Please answer all of the questions below._
- Idea name:Are you an expert web user?
- What is the problem you are solving for: Helping non techs for maintaining their privacy and play safely with websites.
- Who encounters that problem (who is your audience - describe them): 
  users who  have less or no  knowlegde about the web security.
- How will your tool solve this problem for these people:  
  By building  modes inside the browser like - (a)Expert webuser mode (b)Noobie webuser Mode
  (c)___ (d)_____  .We can animate the browsing of the user according to the mode selected. Warning and security alerts can be provided to the user on basis of the mode which will help user to think before taking further actions. If the mode is expert then based on some assumptions about his knowledge about  web security, alerts will be filtered and displayed. If the mode is noobie then a suggestion box will be displayed guiding him how to surf this particular website and how to remain safe and where to provide(or not) your information, alerting him/her about the basic policies of the website.
- What are you going to create (app, add-on, extension, etc.): 
  extension
- What are the next steps for building this tool: 
  we are going to collect data and analysis the type of users on the web and state some browsing mode based on the types of users on the web.
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @wagnerand  @k88hudson

**Comment by wagnerand** [comment]
Adding @bacharakis. Could you give this a look, please?

**Comment by bacharakis** [comment]
Hello @privacyismyth and congratulations for your idea!
Although I find it interesting and promising i have a couple of calcifying questions.

Based on which criteria are you going to show the warning messages for different pages?
Are you going to have a database of known websites which you have already "analyzed" manually and created the messages?

Can you please elaborate?
Thank you so much!

**Comment by charissalaisy** [comment]
@privacyismyth, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @privacyismyth! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
