### ISSUE TITLE
Build the Technology Challenge[ Web Bugs controller ] 

### ISSUE THREAD

**Issue by Saurabhaa** [mozilla/TBTWBuildChallenge#5]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Wings of fire, USICT ,New Delhi,India
- Challenge Contact Person Name: Rajiv Kumar Jha
- Campus Name: University School Of Information and Communication Technology
### Idea Description:

Many websites and net advertisement companies place web bugs on their pages to collect information or access computer data from users.Web bugs are invisible pieces of code that can work and match with cookies to send information to third parties.As mentioned earlier,,the bugs can be used in a more invasive way to capture a visitor's Internet Protocol Address or installing pernicious files in visitors hard drive.For example, web bug launches multiple browser windows when person tries to exit the site.We can control this by putting control over these pop up web pages that come and access visitor's information
_Please answer all of the questions below._
- Idea name:Pop-up Controller
- What is the problem you are solving for: people's private information and data is on stake.
- Who encounters that problem (who is your audience - describe them): 
  anyone who is active online and uses internet for various purposes
- How will your tool solve this problem for these people:  
  Its will prevent any automatic pop up to launch and thus would prevent the web bug to access any personal information of the user
- What are you going to create (app, add-on, extension, etc.): 
  add-on
  - What are the next steps for building this tool: Algo  analysis and design.
- Links to additional information: 

https://www.google.co.in/url?sa=t&source=web&rct=j&url=https://www.computer.org/csdl/proceedings/hicss/2002/1435/07/14350193b.pdf&ved=0ahUKEwjEyOvW9srMAhVRCY4KHfjXA3gQFggbMAA&usg=AFQjCNF0KBh5Sm0IT9OeqFW8rpSe93DR8w

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @brianking

**Comment by abbycabs** [comment]
Thanks for the idea @Saurabhaa!

Any reason why an ad-blocker doesn't do this?

**Comment by brianking** [comment]
Hi @Saurabhaa 

The paper you link to is from 2002, when pop ups were a big problem on the Web. Since then, web browsers have built in pretty good support to control them. So I'm not quite sure what you are proposing on top of that (+ exisiting add-ons like ad blockers that @acabunoc mentions).

**Comment by charissalaisy** [comment]
@Saurabhaa, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll consider going on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about here: https://hackdesign.org/lessons/10.

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @Saurabhaa! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
