### ISSUE TITLE
Build Technology Idea Submission

### ISSUE THREAD

**Issue by Ankurg92** [mozilla/TBTWBuildChallenge#50]
# Build Technology Idea Submission
- Team Name: Avengers ultron 
- Challenge Contact Person Name: ankur Garg 
- Campus Name: ymca University of Science and technology, Faridabad 
### Idea Description
- Idea name: browser login password 
- What is the problem you are solving for: Problem of forgetting log-out the mails /sites before closing the browser
- Who encounters that problem (who is your audience - describe them): generally, people have a habit to left the email or social sites login in the browser to remember mode. And this can lead somebody to see/modify their personal stuff
- How will your tool solve this problem for these people: this tool will ask the user to enter username and password for start using the browser. 
- What are you going to create (app, add-on, extension, etc.):add-on
- What are the next steps for building this tool: 
  Will write code in Javascript of add-on and also learn how to write the Javascript code. 
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @wagnerand  @k88hudson

**Comment by wagnerand** [comment]
Hi Avengers ultron team,

thank you for your contribution.

I am not sure how this proposal "makes people more aware of their privacy and security online" (the topic of this campaign). How exactly would a password popup raise such an awareness?

A simple username/password dialog is of limited help only. If an attacker already has access to the computer, it's easy to just copy the whole profile (or any arbitrary file on the computer), or install keyloggers or other sniffing mechansim, or any malware at all, really.

I see that people leaving their unlocked computer unattended can be an issue, but the vulnerabilities they're left open to are much more than just "see/modify" personal content on websites. Adding a password dialog does not make users safer but might give a false sense of safety.

Also, keep in mind that the deadline for the first prototype of your idea is June 1st. If you have no experience in JavaScript and the add-on ecosystem (not even considering security topics), it might be a challenge.

**Comment by charissalaisy** [comment]
@Ankurg92, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @Ankurg92! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
