### ISSUE TITLE
Avoid Fake Banking Login Screens

### ISSUE THREAD

**Issue by developergoutamdas** [mozilla/TBTWBuildChallenge#51]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: "Developer of Web"
- Challenge Contact Person Name: Goutam Das 
- Campus Name: B. P. Poddar Institute of Management & Technology
### Idea Description

_Please answer all of the questions below._
- Idea name: Identify fake login screens of banks by identifying phishing sites
- What is the problem you are solving for: 

1.Block access of hackers to the users debit/credit card information by creating fake websites.
2. Also inform the customers about the potential threats.
3. Avoid online frauds on PayPal or the malware hijack in Australia.
- Who encounters that problem (who is your audience - describe them): Almost everyone who use online payment suffer from such insecurity. That is why Cash-On-Delivery(COD) is very popular in India. As developers, the onus is on us to give a secure ecosystem to the users.
- How will your tool solve this problem for these people:  

The app will identify the following:
1.Whether there is any change in the new site.
2. Is the website domain old enough by using Scamadviser? [(http://www.scamadviser.com)](url)
3. Does the website possess a 128-bit SSL encryption model?
4. Alexa ranking
5. Using Similar Web API or using similar API from GitHub, we can the users to visualize the rank and reach of a particular app or website.((https://developer.similarweb.com/))[url]
(Note: This app has a sole objective to monitor and inform the customers about the various payment related threats to any banking website or app. It is not intended to be used for e-commerce websites or other payment sites.)
We will be happy to work with any other team with a similar working idea. 
- What are you going to create (app, add-on, extension, etc.): To make an app for the Firefox and Android OS 
- What are the next steps for building this tool: 
  1.To prepare an algorithm (need some help), so that we can start coding.Our team is capable of coding in Java-script and Python.We need a game-plan so that we can incorporate the existing APIs.
  2.We have developed a hypothetical UI on paper and we are trying to produce the same using Adobe Illustrator.
- To reduce data usage and to mitigate low bandwidth problems in developing countries of Africa and Asia, we are hoping to use the cache and history data from browser. We are not quite sure about it because we also want to develop a light app(within 10MB, so that phone users having low internal memory ca still use them) and a great UI !
- Links to additional information: 
  [http://www.smh.com.au/technology/consumer-security/malware-hijacks-big-four-australian-banks-apps-steals-twofactor-sms-codes-20160309-gnf528.html](url)

@LucyeoH                  #49 #

**Comment by LucyeoH-zz** [comment]
Reviewers: @jdm  @k88hudson

**Comment by jdm** [comment]
Hi @Saugatadas! This is an interesting tool idea, and I have a couple questions and some suggestions. First, what do you mean by "Whether there is any change in the new site"? That point is much less detailed and clear than the others in your list. Second, what information will the Similar Web API provide that will help your app accomplish its purpose? I don't know anything about that API, so clarifying that point would be useful. Third, you mentioned wanting to use browser history and cache data to help you - can you elaborate on that? My understanding from your description is that this app might be used when visiting sites for the first time, so how would you plan to make use of existing data? With respect to scamadviser, I did not see a convenient API on that website, so it looks like you may need to perform some website scraping to obtain the data you want from it; for the first prototype, that may require more effort than some of the other pieces in your list.

I'm glad to hear that you have a paper prototype of your UI. What sort of help do you need to "prepare an algorithm", exactly? It sounds like you have some good ideas; perhaps start by building the pieces to retrieve each source of information in isolation, then working to combine them?

**Comment by charissalaisy** [comment]
@Saugatadas, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @Saugatadas! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
