### ISSUE TITLE
VER-MED-IFY

### ISSUE THREAD

**Issue by bharatwaaj** [mozilla/TBTWBuildChallenge#52]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name:  QRONOS
- Challenge Contact Person Name: 
- Campus Name: RAJALAKSHMI ENGINEERING COLLEGE
### Idea Description

_Please answer all of the questions below._
Everybody in this world ought to take medicine at least once in their life time, but stats says that around 68% of them are unaware of the medicine that they are taking. I got a thought what if I made them easier. I have built an android mobile app that identifies a MEDICINE, using IMAGE PROCESSING and tells WHAT MEDICINE it is and WHEN IT EXPIRES and FOR WHAT IT IS TAKEN and other such details once it is scanned. A PROTOTYPE OF IT HAS BEEN BUILT using ANDROID PLATFORM. This will be helpful for the common people to find out the right medicines and are they taking them at the right time.  Once the medicine is scanned using the app, it will automatically popup a button stating the name of the medicine and take the user to buy the medicine online and information about the medicine online on click of the button.
- Idea name: VER-MED-IFY
- What is the problem you are solving for: Healthcare Domain - In order to identify medicines
- Who encounters that problem (who is your audience - describe them): Normal People
- How will your tool solve this problem for these people:  Image Processing
- What are you going to create (app, add-on, extension, etc.): Android App
- What are the next steps for building this tool: Build an app using android studio platform
- Links to additional information: www.qronos.comuf.com

**Comment by LucyeoH-zz** [comment]
Reviewers: @jdm @k88hudson

**Comment by jdm** [comment]
@bharatwaaj This is a very specific problem you're trying to solve, and it sounds like you've got a solution for it. However, this doesn't appear to be related to the issues surrounding privacy and security on the web, which is the point of this campaign.

**Comment by charissalaisy** [comment]
@bharatwaaj, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @bharatwaaj! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
