### ISSUE TITLE
Be aware,avoid risk

### ISSUE THREAD

**Issue by ghost** [mozilla/TBTWBuildChallenge#53]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Web Hunter
- Challenge Contact Person Name: Najneen Rejwana,Kaniz Fatema
- Campus Name: Sher-e-Bangla Agricultural University
### Idea Description

_Please answer all of the questions below._
- Idea name: Self-Consciousness page
- What is the problem you are solving for: It helps People, having lack of consciousness about their privacy and security to understand the importance about it by providing helping information easily.
- Who encounters that problem (who is your audience - describe them): All types of people as it works in online and people are familiar with  website, especially our region
- How will your tool solve this problem for these people:  Here information will give in a easy process that people collect information at the time of their need.Here video,tutorial etc are also added .
- What are you going to create (app, add-on, extension, etc.): Website
- What are the next steps for building this tool: First of all designing a PSD of the website,Writing code,collect information,Make it.
- Links to additional information: 
  http://www.najneenrejwana13.devitems.net/two/

**Comment by LucyeoH-zz** [comment]
Reviewers: @jdm  @k88hudson

**Comment by jdm** [comment]
Hi @najneen13! Websites can be a great way to share information about subjects like security and privacy. Can you be more specific about the information you want to focus on? What will differentiate your site from existing ones like https://staysafeonline.org/, for example? How would people know to visit your site, and what would they learn from it?

**Comment by ghost** [comment]
My focus is specially to create consciousness of all people about their
security by easy process. We may add various features like conversation
section that helps to communicate among people and also they get interest
to visit the site, daily learning topic, game which helps to teach security
easily by playing, continuously updated video, contact number of helpful
security channel etc.. Above all, it should be a user friendly website
where people visit here daily spontaneously.
The difference between my site and reference site is presence of creative
feature, updating information, user friendliness and so on.

**Comment by charissalaisy** [comment]
@najneen13, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @najneen13! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
