### ISSUE TITLE
Awareness thought

### ISSUE THREAD

**Issue by manmeetsinghd188** [mozilla/TBTWBuildChallenge#54]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Privacy boosters
- Challenge Contact Person Name: Manmeet Singh
- Campus Name: DAV Institute of Engineering and Technology
### Idea Description

_Please answer all of the questions below._
- Idea name: General awareness
- What is the problem you are solving for: Non-awareness for the privacy vulnerabilities.
- Who encounters that problem (who is your audience - describe them): The primary person because of whom I am taking part in this campaign is me, as I had been a victim for privacy vulnerabilities.
- How will your tool solve this problem for these people:  It is basically not a tool, it is a thought for public awareness.
- What are you going to create (app, add-on, extension, etc.): I will make people understand the constraints that include privacy.
- What are the next steps for building this tool: Just a thought.
- Links to additional information: no links

**Comment by LucyeoH-zz** [comment]
Reviewers: @jdm  @k88hudson

**Comment by jdm** [comment]
Hi @manmeetsinghd188! Educating people about privacy vulnerabilities is a useful goal, but this proposal doesn't go into any detail about how to accomplish it, or any specific vulnerabilities that people should learn more about. This campaign is all about proposing specific, measurable, demonstrable tools or activities that could help people improve how they experience the web, and this proposal is extremely vague.

**Comment by charissalaisy** [comment]
@manmeetsinghd188, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @manmeetsinghd188! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
