### ISSUE TITLE
Different Window for different users.

### ISSUE THREAD

**Issue by rrshahed** [mozilla/TBTWBuildChallenge#56]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Privacy Keepers BD.
- Challenge Contact Person Name: Rezaur Rahman Shahed.
- Campus Name: United International University (UIU).
### Idea Description

_Please answer all of the questions below._
- Idea name: Different Window for different users.
- What is the problem you are solving for:  We want to solve a privacy issue problem. If we have different password protected window for different users in a same Computer it will be more good. As if while i am using a shared computer i have to log out of every individual website/accounts when i'm turning off that PC or i'm away for my security and privacy. But  if there's a way that we can have a personal password protected Firefox browser window for each user than it will be easier for us to easily manage our accounts and privacy because we don't have to log out of every account when we go away.
- Who encounters that problem (who is your audience - describe them): Our teammates/Classmates.
- How will your tool solve this problem for these people:  People can create their own different accounts in Firefox & protect privacy. 
- What are you going to create (app, add-on, extension, etc.):  add-on or built in function,
- What are the next steps for building this tool: We have to build an Add-on to put this function in the browser.
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @jdm  @k88hudson

**Comment by jdm** [comment]
Hi @rrshahed! It seems like the privacy that you're focusing on is for multiple people using the same computer. In particular, this idea sounds like the [Firefox profiles](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) feature that exists, with password protection added to it. That could be a useful feature, but it doesn't really address the goal of this program: "help people understand why privacy and security is important", where the focus is on online privacy and security on the web, rather than on your local computer.

**Comment by charissalaisy** [comment]
@rrshahed, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @rrshahed! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
