### ISSUE TITLE
Identification Of Fake Redirection in Webpages

### ISSUE THREAD

**Issue by shivambhushan17** [mozilla/TBTWBuildChallenge#57]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: DesigNerds
- Challenge Contact Person Name: Shivam Saxena
- Campus Name: INDERPRASTHA ENGINEERING COLLEGE
### Idea Description

_Please answer all of the questions below._
- Idea name : Identification of Fake Redirection in Webpages
- What is the problem you are solving for:Nowadays many webpages grabs user data through fake offers and fools user by multiple redirection through fake webpages .Sometimes many malwares and adwares are being downloaded in this step too.
- Who encounters that problem (who is your audience - describe them): Everyone who is using internet and surfing the web for his/her desired need.It mainly targets the people aged between 15-25yrs .
- How will your tool solve this problem for these people:  This tool will automatically detect if any fake redirection of webpage is linked with the link on which user has clicked & will warn the user about this issue before opening that webpage.  
- What are you going to create (app, add-on, extension, etc.): Extension
- What are the next steps for building this tool: 1) We will firstly learn how to develop an extension for a browser.
  2) Then Decode the problem so we can implement it asap to get rid from the cited above issue.
- Links to additional information: 
  NA

**Comment by scha11a** [comment]
I think it is same as https://github.com/mozilla/TBTWBuildChallenge/issues/9. May be coincidence!

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Hey DesigNerds!

I love the idea, and an extension seems like a good way to implement it, but I'm a little worried about how your code is going to tell a fake redirection from a normal redirection…  Can you go into a little more detail about that part?

**Comment by mhoye** [comment]
I'm interested in the implementation detail there as well, as well as some broad-strokes ideas about how you'd manage the process for people who may want to pursue those links. What is does the user experience here look like?

**Comment by LucyeoH-zz** [comment]
@shivambhushan17 Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @shivambhushan17! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
