### ISSUE TITLE
Change Password Notifier

### ISSUE THREAD

**Issue by sahilrkalra** [mozilla/TBTWBuildChallenge#58]
**Build Technology Idea Submission**
- Team Name: Privacy Defenders
- Challenge Contact Person Name: Sahil Kalra
- Campus Name: Pune Institute of Computer Technology

**Idea Description**
- Idea name: Change Password Notifier
- What is the problem you are solving for: 
  All people of various age groups ranging from a child to an adult including senior citizens
- Who encounters that problem (who is your audience - describe them): 
  One and all who have an habit of saving passwords in their browser instead of re-entering
  whenever one needs to login in their accounts online.
- How will your tool solve this problem for these people:
  It is assumed to be the best practice to change passwords every 90 days to protect one's online
  account from hackers. But people are so much occupied that they don't remember to do so.
  Also many have a habit to save their passwords in the browser instead of re-entering which
  increases the chances of the account getting hacked by hacker.
  
  So the idea goes this way that this add-on / extension will force the browser to store the date along
  with storing the password and after every 90 days i.e. 3 months will send a reminder to the user to
  change the password which will suggest them and create awareness to follow the best practice
  suggested by ethical hackers.
- What are you going to create (app, add-on, extension, etc.): add-on / extension
- What are the next steps for building this tool: 
  Our team will design the prototype of this tool and then start the coding work followed by testing. 
  We'll be also thinking of additional features which we can provide with this tool.
- Links to additional information: NA

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Hey Privacy Defenders,

while rotating your passwords every now and then is a good idea, I worry that this will encourage people to pick worse passwords, just so that they're easier to remember.  Or worse, use the same password on multiple sites, so that they don't need to remember as many!  Instead of asking them to create a new password every three months, could you automatically generate a new password for them?

**Comment by sahilrkalra** [comment]
Hey Blake,
I suppose if we generate a new password for a user ever three months instead of asking them to change then it would be difficult for them to remember & login from different systems where they haven't saved their password.
Anyways leaving that aside it is possible to implement that functionality.

**Comment by bwinton** [comment]
Yeah, there are definitely challenges there, too…

**Comment by sahilrkalra** [comment]
Yeah, can I get your email id please?
I need your guidance regarding its development work.

**Comment by bwinton** [comment]
I think it would be better to continue discussing it here, so that everyone can see the answers to questions they probably also have!  🙂

**Comment by mhoye** [comment]
For what it's worth, I'm not sure if age on its own is a useful requirement of password change, but I think that there's a good idea in here for "last logged in" information for people who'd like to minimize their attack surface, and maybe as part a new perspective on an active password-healthiness service.

"You haven't logged in to this account in 6 months - would you like to close your account with this service?" might be very useful, and I can think of a few others.

**Comment by sahilrkalra** [comment]
Yes, that could be one additional feature which we should include!

**Comment by LucyeoH-zz** [comment]
@sahilrkalra  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @sahilrkalra! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.

**Comment by sahilrkalra** [comment]
Hey! @LucyeoH & @charissalaisy I've attached the prototype (Prototype.pdf), Please find the attached file :)
[Prototype - Change Password Notifier.pdf](https://github.com/mozilla/TBTWBuildChallenge/files/309559/Prototype.-.Change.Password.Notifier.pdf)
