### ISSUE TITLE
IFTTT to support MozData

### ISSUE THREAD

**Issue by amitkumarj441** [mozilla/TBTWBuildChallenge#59]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: UIET CodeGeeks
- Challenge Contact Person Name: Amit Kumar Jaiswal
- Campus Name: University Institute of Engineering & Technology, Kanpur University
### Idea Description

_Please answer all of the questions below._
- Idea name: IFTTT integration to support MozData
- What is the problem you are solving for: 
1. Using Task automation tool IFTTT for things like integrating vast data on Mozilla which supports
   MozData such as Mozilla Support(SUMO), AoA, Localization Metrics etc. , integrating links with the   help of various triggers.
2. One important feature of IFTTT is recipes that give us the ability to make this a very powerful automation resource. 
3. Weather being one such example. Weather is "this" sources as a trigger; like an email invite on Hike, only if the weather turns out to be good, no need to go on computer and click "send" which is a kind of automation than can save our time.
- Who encounters that problem (who is your audience - describe them): Almost everyone who visit Mozilla Support on Twitter, SUMO and Localization Community.
- How will your tool solve this problem for these people:  
  Following are the list of proposed triggers to achieve my goal of implementing the triggers to support MozData

1.1. Modify Item

1.2. New feed item( fires every time a new item is added to the feed you specify)

1.3. Delete item

1.4. New feed item matches( fires every time a new item in the feed you specify contains a particular keyword or phrase)

1.5. Release at once
- What are you going to create (app, add-on, extension, etc.): Web route or extension.
- What are the next steps for building this tool: 
- It requires the use of HTML, CSS, Python(Flask). Our team is capable of coding in HTML, CSS and Python.
- We have developed a hypothetical idea of implementation on paper and we are trying to produce the same.
- Links to additional information: 
  IFTTT( If this, then that) : https://ifttt.com/
  IFTTT Wiki: https://en.wikipedia.org/wiki/IFTTT

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Hey UIET CodeGeeks!

So, funny story: I actually worked on an IFTTT Firefox integration (which you might be able to see a presentation on [here](https://air.mozilla.org/mozlando-dino-tank/))…  And this does sound like a reasonably useful thing to have.

Having said that, I'm not sure how this fulfills the mission of mobilizing communities toward “a safer, more secure Web”, so perhaps you could expand on that…

**Comment by mhoye** [comment]
I think there's the seed of a promising idea here, but I would like to hear a user story or two. "For some problem X, if user does Y, this feature does Z, solving the problem" or something to that effect. IFTTT is a pretty loosely-defined toolbox, so it would be nice to know we'd be building towards a reasonably specific, well-understood outcome.

**Comment by amitkumarj441** [comment]
Hey @bwinton,

Glad to hear you.
That's great! I like this presentation and idea too.
@mhoye We just come up with our contemplated idea and we would like to implement for the same.
We already mentioned above in our proposal that we're building a web route or extension, but we need your suggestion for the next step.
Thank you for your time and consideration.

Cheers,
Amit Kumar Jaiswal

**Comment by LucyeoH-zz** [comment]
@amitkumarj441  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by amitkumarj441** [comment]
@LucyeoH Here is the Link to my code [Github Repo](https://github.com/amitkumarj441/Mozilla-Technology-Challenge)

**Comment by amitkumarj441** [comment]
@LucyeoH Please let me know what is meant by "**Your picture**"

**Comment by bacharakis** [comment]
HI @amitkumarj441 and thanks for submitting your prototype!
Can you please add some instructions on how to install and use it?

It would be extremely helpful to include some examples which will have an effect on MozData. For example which IFTTT rule will trigger what, and how this helps Mozilla?
