### ISSUE TITLE
Build the Technology Challenge [Data strength detector tool]

### ISSUE THREAD

**Issue by rjrajivjha** [mozilla/TBTWBuildChallenge#6]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Wings of fire, USICT, New Delhi, India
- Challenge Contact Person Name: Rajiv Kumar Jha
- Campus Name: University School of Information and communication technology
### Idea Description

_Please answer all of the questions below._
- Idea name: Password Detector
- What is the problem you are solving for: We are solving every other's guy problem who are online.
  some start-ups or new companies so save the data like email-id, password,personal details. ans as day by day these websites are increasing, their quality is also decreasing. They are easily hackable. So if they save user's data in direct text format, hacking of organization's db might hurt user's privacy.
- Who encounters that problem (who is your audience - describe them): online users
- How will your tool solve this problem for these people:  This will help them detect whether the data is being saved in direct text format or any encryption is being done or not.
- What are you going to create (app, add-on, extension, etc.):  add-on
- What are the next steps for building this tool: algorithm designing
- Links to additional information: none.

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @brianking

**Comment by abbycabs** [comment]
Thanks for the idea proposal @rajivjhaimin! I'm not sure you'll be able to detect how a website is handling your information. When you say 'algorithm designing' - do you already have an idea how this will work?

**Comment by rjrajivjha** [comment]
Yeah, i have an idea, but i am not sure about it's legality. I have asked others too, but they asked me to put the idea on list and afterwards mentors will help me out to solve this issue.

**Comment by brianking** [comment]
It seems like such a tool already exists: http://plaintextoffenders.com/tools

**Comment by charissalaisy** [comment]
@rajivjhaimin, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about here: https://hackdesign.org/lessons/10. 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @rajivjhaimin! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
