### ISSUE TITLE
Personal Contact Account Privacy

### ISSUE THREAD

**Issue by ghost** [mozilla/TBTWBuildChallenge#60]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: TechWeb
- Challenge Contact Person Name: Md. Maruf Rahman
- Campus Name: BRAC University
### Idea Description

_Please answer all of the questions below._
- Idea name: PersonalContentPrivacy
- What is the problem you are solving for: Privacy of anyone's account information
- Who encounters that problem (who is your audience - describe them): If any person logs into his mail or any kind of social media and his information is shared then this problem can arise
- How will your tool solve this problem for these people:  People can see that what information of their account are being compromised and for how much money the information is shared
- What are you going to create (app, add-on, extension, etc.): An extension for browser
- What are the next steps for building this tool: Creating the prototype and then build the user interface and build the extension
- Links to additional information: NA

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Hey TechWeb!

So, you've described when the problem can show up, and how it's related to privacy and a secure web, but I'm not clear what the problem is, or how you're proposing to fix it…  Can you elaborate on those a little more?

**Comment by mhoye** [comment]
I would also like to hear a more specific description of the problem you're trying to solve, and a user story or two. 

End-to-end all-encompassing privacy solutions - like, screen to distant server and back again - are staggeringly difficult to implement (nobody's managed so far), but local-machine-only privacy is reasonably straightforward and mostly a solved problem. If I'm understanding this correctly, you're proposing something in between those two extremes, and I'm hoping you can elaborate on it in greater detail.

**Comment by LucyeoH-zz** [comment]
@mMARUF  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @mMARUF! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
