### ISSUE TITLE
Network Intrusion detection.

### ISSUE THREAD

**Issue by sam1681995** [mozilla/TBTWBuildChallenge#61]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: The Privacy Guardians
- Challenge Contact Person Name: Saumya Shandilya,Shiwani Singh
- Campus Name: Symbiosis Institute of Technology
### Idea Description

_Please answer all of the questions below._
- Idea name:Network intrusion detection
- What is the problem you are solving for:
  These days hacking attacks like DDOS attacks are on a rise and people are unaware of any kind of hacking attempt or intrusion into their systems.
- Who encounters that problem (who is your audience - describe them): Any internet user or even any computer user's data is at the risk of getting leaked or their accounts getting hacked.So this will be a general solution.
- How will your tool solve this problem for these people:  It will tell the user if their systems are probable to be hacked.
- What are you going to create (app, add-on, extension, etc.): 
  Yet to decide.
- What are the next steps for building this tool: 
  We are still studying about this.
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Hey Privacy Guardians!

I love your idea, but I'ld like to see a little more info on _how_ you're going to figure out if a system is probably going to be hacker, and also what you would do (or ask the user to do) to make it less hackable…  Also, you know, figuring out what you're going to create and filling out the next steps would be good.  😃

**Comment by mhoye** [comment]
"Personal IDS" sounds good, but pretty difficult - the user stories are straightforward, but if you can detect the change of state that would indicate an intrusion, would the better approach be prevention? 

I'd like to know more about the implementation details of this in terms of how it might work, and where it might live on a network. A network hub willing to learn traffic patterns or a scanning tool could be interesting work, but it's difficult to see how it would be effective at the endpoints. Can you describe in some detail how this would work?

**Comment by LucyeoH-zz** [comment]
@sam1681995  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @sam1681995! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
