### ISSUE TITLE
Improve Ux feature of mozilla's private window 

### ISSUE THREAD

**Issue by dbms** [mozilla/TBTWBuildChallenge#62]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name:  Wings of fire, USICT, New Delhi, India.
- Challenge Contact Person Name: Rajiv Kumar Jha
- Campus Name: University School of Information and Communication Technology.
### Idea Description

_Please answer all of the questions below._
- Idea name:Private window bug in mozilla 
- What is the problem you are solving for: 
  By using private window mozilla ensures that your browsing history will not be saved in your browser. But in mozilla when we open a tab in private window and then close it, then one can know the tabs you opened in private window by using ctrl+shift+t. This indirectly means mozilla is somehow storing your private window browsing history. Private window has no meaning if you can track the history of tabs simply with a hot key.  
- Who encounters that problem (who is your audience - describe them): 
  all mozilla users who doesn't want to use ctrl+shift+t feature in private window.
- How will your tool solve this problem for these people:  
  our add-on will open mozilla's private window that disable tab tracking and provide the feature to the users.
- What are you going to create (app, add-on, extension, etc.): 
  add-on
- What are the next steps for building this tool: 
  crawl the mozilla open source community and gather information related to the mozilla private window to build this awesome add-on
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Hi Wings of fire.

To start with, as someone who works on Firefox, I find the title of your issue to be rather disappointing.  Perhaps you disagree with the way the private window has been implemented, but disparaging it doesn't really make the people who worked on it inclined to want to help you…  Just a thought.

Now, for the content of your idea: I sort of agree with you that it's kind of surprising that ctrl-shift-t works, but I can also understand the difference between things being stored in memory and things being stored on the hard disk, and if you close the private browsing window then those tabs are gone, and untrackable…  (There's also a user experience component here, where people often mistakenly close tabs, and would like to be able to get them back, even in private browsing mode.)

So, I guess this is the part where I offer suggestions…  On the whole, I think it's a good idea for an add-on.  It would probably go over better if you use a more professional tone (don't call people lazy; don't suggest that features "have no meaning", or "suck"; that sort of thing).  You could also do some research into [why the feature is the way it is](https://bugzilla.mozilla.org/show_bug.cgi?id=961380), and take that into account in your proposal.

Good luck!

**Comment by rajivjhaimin** [comment]
Hey 
@bwinton 

Greetings from Wings of fire,

We are sorry, for the abusive and unprofessional language used by our team-member. We apologise and our taking back his words.
But we really want to implement this idea, in order to give user one more option , which will increase its UX only.

Thanks and Regards
Wings of fire

**Comment by dbms** [comment]
Thanks @bwinton 
I didn't intended to mean that.
I have updated the proposal.

**Comment by privacyismyth** [comment]
Hey 
@bwinton

Greetings from Wings of fire,

We are sorry, for the abusive and unprofessional language used by our team-member. We apologise and our taking back his words.
But we really want to implement this idea, in order to give user one more option , which will increase its UX only.

Thanks and Regards
Wings of fire

**Comment by bwinton** [comment]
Thank you both.  As I mentioned, I think it's a good idea for an add-on, and hope you continue on to implement the idea!

**Comment by LucyeoH-zz** [comment]
@privacyismyth Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @privacyismyth! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
