### ISSUE TITLE
# Build Technology Idea Submission by Swaviman Mohapatra(team mozilarock)

### ISSUE THREAD

**Issue by swavimanm60** [mozilla/TBTWBuildChallenge#63]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: mozialrock
- Challenge Contact Person Name: Swaviman Mohapatra
- Campus Name: Trident Academy Of Creative Technology
### Idea Description

_Please answer all of the questions below._
- Idea name:cloud security
- What is the problem you are solving for:To solve basic cloud security means online data 
- Who encounters that problem (who is your audience - describe them):university student 
- How will your tool solve this problem for these people: first of all raise awareness about online seurity and our tool will be protect online data of them it may facebook data or twiter data.
- What are you going to create (app, add-on, extension, etc.): extension
- What are the next steps for building this tool: do coding for it
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Hello team mozialrock!

I think I'ld like to see a little more detail about what sorts of cloud security problems you're trying to solve, and how your tool will protect the online data…  Thanks!

**Comment by swavimanm60** [comment]
Hello sir 
        Thanks for comment and i am going to explains in details below.
Organizations planning to federate identity with a cloud provider need to understand the security measures the provider uses to protect the identity platform.Centralizing identity into a single repository has its risks.So facing this scenario i gonna create a multi-factor authentication system for user means  in client side not in server .It's kind of extension which is deployed in browser.When you going to Facebook page it automatically detect and multi-factor authentication page will come and you have to give your password which is you register before on this page and after that it automatically taken over you that site it may be facebook,twitter  and again you give your own facebook password as usual before.

**Comment by mhoye** [comment]
This is a hard problem, but I applaud you for taking a run at it. I would also like to hear some more about the specific problems you'd like to solve, and some user stories about your proposed solution.

**Comment by LucyeoH-zz** [comment]
@swavimanm60 Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @swavimanm60! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
