### ISSUE TITLE
Friend data plug-in

### ISSUE THREAD

**Issue by harshbhardwajcsit** [mozilla/TBTWBuildChallenge#64]
# Build Technology Idea Submission

_Please answer all of the questions below._
- **Team Name:** TechSaiyanz
- **Challenge Contact Person Name:**harsh bhardwaj 
- **Campus Name**: swami keshvanand Institute of technology,jaipur

**### Idea Description**
_Please answer all of the questions below._
 **Idea name**: Friend data plug-in
- **What is the problem you are solving for**:  solving the problem of user Data transparency ,our plugin will try to list the websites that are consuming  maximum of the user's data .Plugin will reduced the data usage when users have limited data  availability and also reduce the data usage when user would not working with browser  .
- **Who encounters that problem (who is your audience - describe them):** The people having limited data availability or those people who prefer lower data consumption during browsing .
- **How will your tool solve this problem for these people:**  our plugin will try to list the websites that consume  maximum of the user's data ,plugin will reduced the data usage when users have limited data  availability and also reduce the data usage when user would not working with browser  .
- **What are you going to create (app, add-on, extension, etc.):** 
  we will go with Plug-in
- **What are the next steps for building this tool:** 
1. will develop the prototype of plugin.
2. will checkout the website that stored maximum cookies at browser.

3.try to create a sleep mode extension for browser to restrict the wasted of data usage when user is inactive. 
- Links to additional information: 
  http://www-static-blogs.operacdn.com/multi/wp-content/uploads/sites/4/2016/02/study-shows-30-percent-mobile-data-is-wasted-on-background-data1.jpg

https://drive.google.com/open?id=0B0OY6NWGDOBOQUhlYWdVNzJyMms

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Hey TechSaiyanz!

This would be a very useful plugin, and your idea's strength is over 9000 😃, _but_…

I think the point of this campaign is to highlight how people's personal data gets spread further than they think it might, as opposed to how many megs of data is getting downloaded.  I don't know if you can modify the idea to be more about privacy, but that would probably fit in better with the campaign.

**Comment by LucyeoH-zz** [comment]
@harshbhardwajcsit  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @harshbhardwajcsit! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
