### ISSUE TITLE
TBTW Technology Challenge Idea

### ISSUE THREAD

**Issue by ghost** [mozilla/TBTWBuildChallenge#65]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: 
- Challenge Contact Person Name: Anubha Maneshwar
- Campus Name: SRPCE Nagpur
### Idea Description

_Please answer all of the questions below._
- Idea name: Android App for detection
- What is the problem you are solving for: There are people who are using different websites from their mobile. And they don't know which websites are tracing them. So we are solving this problem.
- Who encounters that problem (who is your audience - describe them): All the people having an Android phone.
- How will your tool solve this problem for these people:  Our App shows the records of website you visited on daily basis and which websites tracked your activities. It will notify you on regular intervals.
- What are you going to create (app, add-on, extension, etc.): app
- What are the next steps for building this tool: collect data from the users and add additional features.
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Hello Anubha,

I'm not familiar with Android's API, can you record all the websites people visit from an app?
I'm also curious as to how you will figure out which websites track your activities…

But other than those two questions, I think this is a pretty solid idea!  Thanks!

**Comment by LucyeoH-zz** [comment]
@anubham  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @anubham!

Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
