### ISSUE TITLE
Key-log Blocker

### ISSUE THREAD

**Issue by Rishabhlavi** [mozilla/TBTWBuildChallenge#66]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: TFC Intimite
- Challenge Contact Person Name: Rishabh Chandrayan
- Campus Name: Truba Institute of Engineering and Information Technology
### Idea Description

_Please answer all of the questions below._
- Idea name: Key-log Blocker
- What is the problem you are solving for: 
  Prevention from potential threats from online as well as offline key loggers which tracks and records the keystrokes from the keyboard and access information like passwords which an be the most dangerous threat to the users privacy and security.  
- Who encounters that problem (who is your audience - describe them): 
  Our Audience is the common public whose daily usage includes banking, social media, and other stuffs which require an account for login in using password. 
- How will your tool solve this problem for these people:  
  Our tool will include a 3x3 pattern lock which will be directly connected with the user's email account in which he will save all the passwords using their personal computer when initially prompted and will draw a pattern which will be saved as the pattern lock password. Now, with it when person will login in any other PC then first he will enter his email id (step 1 auth.) after which he will be asked to enter the password in a random order (so that the host of key logger an not understand what exactly user typed)  and below which a pattern lock system (as used in several smartphone) will appear of 3x3 dots. Now the user will draw same pattern as he had set on the time of initialization on his PC. and Voila! The password will arrange itself and user can copy it and paste on the login password field. No way trackers can track the user.
- What are you going to create (app, add-on, extension, etc.):
  We are thinking to create a add on or an extension to Firefox browser which can help people with there privacy. Also as it will be opensource this idea may also be used on smartphones and smart watches by other Browsers. We would like some suggestion on it like what to make either an add on or extension to Firefox.
- What are the next steps for building this tool: 
- Identify and observe the behavior of key-logger threats and ways to avoid them
- Preparing an Algorithm for understanding the logic of idea
- Work with JavaScript and i think it may also take some pythons skills too.
- Assigning roles to teammates about there work on the add on/extension 
- Will need professional assistance regarding the idea from staff and coaches.
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Hello TFC Intimite,

I think you have a very strong proposal here.  It seems like it will be fairly tricky both to implement technically and to get it to a point where it will be easily usable by many people, but with hard work I believe you can pull it off.

Good luck!

**Comment by mhoye** [comment]
I agree with bwinton, this is a difficult but interesting problem, and I'm interesting in learning more about your proposal.

**Comment by Rishabhlavi** [comment]
Hey there @bwinton @mhoye 
This was a problem which I myself faced and was trying to find an easy but effective solution for it.

We are now in initial stage of designing algorithms and building a prototype. . We started with an idea to design some rough images like how it may look or how we a user an access the it. This will make everyone clear about what we will make and how how it will work. A soon as they are ready, i will update them here.

Well surely this will be a difficult task and also as all my team mates are newbie in making plugins or extension,its may become a bit more difficult. But with some guidance and help from yours this can be done, we will do our best to make it.

Thank You

**Comment by LucyeoH-zz** [comment]
@Rishabhlavi  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @Rishabhlavi !

Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
