### ISSUE TITLE
Whack the Hack

### ISSUE THREAD

**Issue by sumilmehta** [mozilla/TBTWBuildChallenge#67]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Baker Street Boys
- Challenge Contact Person Name: Sumil Mehta
- Campus Name: Amity School of Engineering & Technology, New Delhi
### Idea Description

_Please answer all of the questions below._
- Idea name: whack the hack
- What is the problem you are solving for:
- Who encounters that problem (who is your audience - describe them): Day to day users who use SNS, Online shopping , Net-Banking etc
- How will your tool solve this problem for these people:  We are going to create a website which will aware people about the various blunders that can happen on the internet and how to prevent them.We will also put tutorials regarding them.
- What are you going to create (app, add-on, extension, etc.): Web-Site
- What are the next steps for building this tool: We will prepare the basic layout and gather the suitable information.Then we will prepare some interesting and informative tutorials regarding the prevents of the attacks
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Hi Baker Street Boys!

I like the idea behind this, but I think you could make it even better by including the community a little more.  Maybe ask people for their tips, or stories of blunders they've made, and post them anonymously?

Oh, also you could fill out the "What is the problem" section.  😃

**Comment by sumilmehta** [comment]
Ohh, sounds great
We look at it

**Comment by LucyeoH-zz** [comment]
@sumilmehta  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @sumilmehta!

Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.

**Comment by sumilmehta** [comment]
Youth4workHi ,Sumil Mehta, your contact & who has this profileSuggests you to try a quick, 5 min, Online Skill test to know your own skillshttps://www.youth4work.com/onlinetalenttestIt’s a fun test that helps you know where you stand for your skills across the globe. It also helps you get professional opportunities.Regards,Youth4workUnsubscribe
