### ISSUE TITLE
Technology Challenge

### ISSUE THREAD

**Issue by ghost** [mozilla/TBTWBuildChallenge#68]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Privacy Lovers
- Challenge Contact Person Name: Soumya Jindal
- Campus Name: Bhagwan Parshuram Institute of Technology
### Idea Description

_Please answer all of the questions below._
- Idea name: Data Flow
- What is the problem you are solving for: The need to understand the ways personal data is crawled, stored and used on the web.
- Who encounters that problem (who is your audience - describe them): The problem focuses on people of all ages.
- How will your tool solve this problem for these people: The tool is an extension or a plugin that keeps a track of the site being visited by the user, it's potential threat value and pops up an alert when it is unsafe or tries to phish data. It keeps track of the personal details provided by the user and consumed by the site and the way it may be used further in the future. It keeps a note of the way the sites may access data from my social media profiles and memory and give us regular alerts of any such data theft.
- What are you going to create (app, add-on, extension, etc.): Extension
- What are the next steps for building this tool: The coding for the extension.
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Good afternoon (or evening), Privacy Lovers!

So, I've been trying to give suggestions on how to make submissions better, but I think you've hit the sweet spot with this one.  The only thing I can think of suggesting might be to add a few more details on who you're going to figure out the potential threat value of a website, and how you'll know if it's unsafe or tries to phish data.  But other than that, good job!  :)

**Comment by ghost** [comment]
Thank you for your review! The entire idea intends to bring various scattered security tools under one umbrella, all integrated into the browser.

We aim to provide a feature which alerts the user if the website being accessed seems to be unsafe or may constitute malware by tapping in to the cookies, images, JavaScript, plug-ins, pop-ups, sandboxing, location sharing and HTTPS and SSL settings.

To prevent Phishing, the attempt to acquire sensitive information, often for malicious reasons, by masquerading as a trustworthy entity in an electronic communication, the feature will scan thoroughly for any insecure element in the window. Also it aims to alert the user against any surveillance softwares such as keyloggers.
The data is ensured to be used such that it makes the user's experience on the web immersive and custom, yet secure and not a victim of data thievery. Thus the user, rather than the developer, has the control of their  own data.

**Comment by LucyeoH-zz** [comment]
@JindalSoumya  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @JindalSoumya!

Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
