### ISSUE TITLE
Firefox Technology Challenge

### ISSUE THREAD

**Issue by SrinivasChoudhury** [mozilla/TBTWBuildChallenge#69]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Code Rockers
- Challenge Contact Person Name: Srinivas Choudhury
- Campus Name: National Institute of Science and Technology
### Idea Description

_Please answer all of the questions below._
- Idea name:MeetPoint
- What is the problem you are solving for:Developing an add-on which enables chatting with other peoples on the same network(Intranet)...Focusing a college campus.
- Who encounters that problem (who is your audience - describe them): 
  People who are accessing intranet inside a college campus.
- How will your tool solve this problem for these people:  
  Providing an end to end encrypted chatting service for intranet users.
- What are you going to create (app, add-on, extension, etc.): 
  Add-On/Extension
- What are the next steps for building this tool: 
  Building the app using latest Agile methodology
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Hello Code Rockers!

I like the idea behind this, but think you could use a little more focus on the privacy aspects of the submission…  I would also suggest creating a website that uses WebRTC instead of an add-on, so that it would also work on the Chrome, Opera, and Android browsers…

Rock on!  :)

**Comment by LucyeoH-zz** [comment]
@SrinivasChoudhury  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @SrinivasChoudhury!

Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
