### ISSUE TITLE
Build Technology Idea Submission[Y:Let us know]

### ISSUE THREAD

**Issue by Saurabhaa** [mozilla/TBTWBuildChallenge#7]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Wings of Fire, USICT, New Delhi, India
- Challenge Contact Person Name: Rajiv Kumar Jha
- Campus Name: University School of Information and Communication Technology
### Idea Description

_Please answer all of the questions below._
- Idea name: Y
  ,"Let us know" -Tag line
- What is the problem you are solving for:
  Survey shows that people are more comfortable  if they see a privacy statement & are more assured if privacy statement has been approved by a third party such as TrustE.
  Not all websites tell :1)whether it collects any personal data  in any form including cookies,
  2) the purpose of collecting the the data,
  3)If it has a privacy policy statement.
- Who encounters that problem (who is your audience - describe them): 
  Each individual who makes online transactions ,use e-mail services,or surf any online website.
- How will your tool solve this problem for these people:  
  An extension would be used to record the presence or absence of each of 3 attributes(Personal info,Purpose,Privacy statement) in a website and that particular website would be rated according to people who surf these websites.
  1)About personal info it would be rated according to:How protected ones personal information is and what info is asked by the website other than basic purpose of that website.
  2)About Purpose it would be rated according to the level of information provided by the website on how would they use this personal information of user for themselves or other purposes.
  3)About privacy statement it would rated on 2 parameters: 1)If a website does/does not have a privacy policy statement,2)How accurate their privacy policy statement is in accordance with their website and activities.
- What are you going to create (app, add-on, extension, etc.): Extension
- What are the next steps for building this tool: We are going to grab some ideas which will address this issue in the team brain storming session.After that we'll design our algorithm.
- Links to additional information: 
  https://www.google.co.in/url?sa=t&source=web&rct=j&url=https://www.computer.org/csdl/proceedings/hicss/2002/1435/07/14350193b.pdf&ved=0ahUKEwjEyOvW9srMAhVRCY4KHfjXA3gQFggbMAA&usg=AFQjCNF0KBh5Sm0IT9OeqFW8rpSe93DR8w

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @ScottDowne

**Comment by abbycabs** [comment]
Hi @Saurabhaa, thanks for the project idea! Crowdsourced information on a website's privacy policies would be very useful. Gathering this info would help everyone understand the current landscape of web privacy. What value would your extension bring to it's users (ie the people adding this information)? Why are they motivated to record this information for you?

**Comment by charissalaisy** [comment]
@Saurabhaa , thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about here: https://hackdesign.org/lessons/10. 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @Saurabhaa! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
