### ISSUE TITLE
PRIVATE KS KEY

### ISSUE THREAD

**Issue by bolasoma** [mozilla/TBTWBuildChallenge#71]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: THE COMMUNITY CHANGEMAKERS
- Challenge Contact Person Name: : ADOU FREDERIC
- Campus Name: UNIVERSITY FELIX HOUPHOUET BOIGNY OF COCODY-ABIDJAN
  
  ```
   # ##      **---------------- ENGLISH / ANGLAIS -----------**
  ```
### Idea Description

_Please answer all of the questions below._
- Idea name: PRIVATE KS KEY
- What is the problem you are solving for: SOLVE THE PROBLEM OF PRIVACY AND OF ONLINE DISCRETION 
- Who encounters that problem (who is your audience - describe them): THE COMMUNICATION AND DATA OF STUDENTS OF COTE D’IVOIRE ARE CONFRONTED BY OR FACING TRACING, SPY AND PIRACY BY THE MANY SET UP SPY APPLICATION AND SOFTWARE. 
- How will your tool solve this problem for these people: PRIVATE KS KEY  WILL ALLOW A SAFE COMMUNICATION PRIVATE OF USERS. THAT IS TO SAY THAT ANYBODY CAN HAVE A PRIVAT COMMUNICATION BY VOICE, BY CHAT AND VIDEOS, WITHOUT GETTING OUR CONVERSATIONS HEARD BY ANYBODY. IT WILL BE GUARANTED BY A PRIVAT KEY. IT WILL ALLOW ALSO TO SAIL ON INTERNET WITHOUT COOKIES. THAT IS TO SAY THAT NOBODY CAN KNOW THE WEB SITE THE USERS VISIT OR USE. 
- What are you going to create (app, add-on, extension, etc.): APP AND EXTENSION
- What are the next steps for building this tool: N/A
- Links to additional information: N/A
  
    # ##      **---------------- FRANCAIS / FRENCH   -----------**
### Idea Description

_Please answer all of the questions below._
- Idea name: PRIVATE KS KEY
- What is the problem you are solving for: RESOUDRE LE PROBLEME DE VIE PRIVÉE ET DE DISCRETION  EN LIGNE 
- Who encounters that problem (who is your audience - describe them): LES COMMUNICATIONS ET LES DONNEES DES ELEVES ET ETUDIANTS DE COTE D`IVOIRE SONT CONFRONTEES  AU TRAQUAGE, A L`ESPIONNAGE ET AU PIRATAGE PAR LES MULTIPLES APPLICATIONS ET LOGICIELS ESPIONS INSTALLÉS. 
- How will your tool solve this problem for these people:  PRIVATE KS KEY  VA PERMETTRE UNE COMMUNICATION SAINE ET PRIVE  DES UTILISATEURS.  CELA  VEUT DIRE QUE N`IMPORTE QUI PEUT AVOIR UNE COMMUNICATION PRIVE PAR VOIX, PAR CHAT ET PAR VIDEO, SANS QUE PERSONNE NE PUISEE ECOUTER SES CONVERSATIONS. IL SERA GARANTI PAR UNE CLE PRIVEE. IL VA PERMETTRE EGALEMENT DE NAVIGUER SUR INTERNET SANS COOKIES. C`EST-A-DIRE QUE PERSONNE NE PEUT CONNAITRE LES SITES WEB QUE LES UTILISATEURS VISITE. 
- What are you going to create (app, add-on, extension, etc.): APP
- What are the next steps for building this tool: N/A
- Links to additional information: N/A

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Hi Community Changemakers,

your proposal seems quite nicely tied into the themes of this campaign, and I think it's probably a good thing to build, but I do worry that it might be a little ambitious.  Still, better to aim high, right?  😀

I think the only thing I would recommend is to add an English translation of your proposal, because a depressingly large number of English speakers can't speak French (me among them).  😉

**Comment by bolasoma** [comment]
@bwinton , thanks we will

**Comment by LucyeoH-zz** [comment]
@bolasoma  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by bolasoma** [comment]
Awesome, thanks @lucyeoH

**Comment by charissalaisy** [comment]
Hey @bolasoma,

Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.

**Comment by bolasoma** [comment]
Thanks @charissalaisy
