### ISSUE TITLE
Second Eye Of Blind(A Smart system for blind person)

### ISSUE THREAD

**Issue by mehakmarium** [mozilla/TBTWBuildChallenge#72]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: 
  • Mehak Marium(2k13/BSIT/38)  From IICT DEPARTMENT SINDH UNIVERSTY OF JAMSHORO
  • Momina qazi(2k13/BSIT/91) From IICT DEPARTMENT SINDH UNIVERSTY OF JAMSHORO
  • Shakila jawed(2K13/BSIT/126) From IICT DEPARTMENT SINDH UNIVERSTY OF JAMSHORO
- Challenge Contact Person
  • Name: MEHAK MARIUM (03472808988)
- Campus Name: SINDH UNIVERSITY OF JAMSHORO SINDH
### Idea Description

Today our world is totally dependent on technology a common person have huge aware of facility to use in daily life technology so why blind person cannot able to enjoy with this awareness So,   Our system SECOND EYE OF BLIND (SEOB) is basically reached and the purpose to make SECOND EYE OF BLIND (SEOB) is to help blind person who is not aware to use application of smartphone, and due to blindness blind majority did not educated so our system can provide the education , awareness to use application of mobile phones for example  blind person in emergency did not dial a call , blind do not write a message if he/she want to send some message to his or her contacts, and also he/she did not see the receive messages and read the message and if blind person was go to anywhere like school so family member does not identify where his or her member is located and also blind  did not read a book so with the help of our system blind can listen the books of library .Our system provide the education,  and security through mobile phone and currently location and provide the notification to member and also so many things we provide to blind person with the help pf our system . our purpose that we reduce the blind person un awareness majority and increase the number of blinds can enjoy a common life like a common person  and do not feel shay or uncomfortable front of common person and blind person feel and increase confidence . 
_Please answer all of the questions below._
- Idea name:
  Second Eye Of Blind (A Smart System For Blind Person)
- What is the problem you are solving for:
  Blind cannot see books,  ca not read messages , cannot aware of education, cannot feel like a common person and able to use application of mobile and dial calls and receives and also family member can locate where his or her member is present and favorite contact can connected to blind person and  we solve the problem of huge blind person can uneducated and do not aware to use application and family member do not feel comfortable due to blind security so we provide all this awareness and blind can feel and enjoy like a common person and family member can feel free and get auto security of her or his member and we reduce the majority of uneducated blind person .
- Who encounters that problem (who is your audience - describe them): 
  Our supervisor LECTURURE MUHAMMAD  BILAL SHAIKH INFORMATION TECHNOLOGY DEPARTMENT IN  UNIVERSITY OF SINDH.
- How will your tool solve this problem for these people:  
  Our  tool help us to use application of mobile phones like :
  • Dial call and receive calls
  • Write messages and read messages with the help of application
  • With the help of camera  blind listen the books of library 
  • Provide web application to family member and family member can recognize where blind person is currently located and what is the today  time detail and member can also notify with its own mobile phones.
- What are you going to create (app, add-on, extension, etc.): 
  We create a dynamic web application as well as android app.
- What are the next steps for building this tool: 
  Our next step is to  meet with a subject in education system and gather requirement and after gather information will build application software for android.

**Comment by LucyeoH-zz** [comment]
Reviewers: @bwinton @mhoye

**Comment by bwinton** [comment]
Hello team!

While I wholeheartedly support your idea, I'm not entirely sure how it relates to this campaign's theme of privacy and security on the internet…  (I also feel like many of the devices on the market today have assistive technologies built in, which helps.)

Good luck!

**Comment by mehakmarium** [comment]
Thank you sir to appreciated me ...

**Comment by LucyeoH-zz** [comment]
@mehakmarium  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @mehakmarium!

Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.

**Comment by mehakmarium** [comment]
sir where i submit my prototype?

**Comment by mehakmarium** [comment]
![8](https://cloud.githubusercontent.com/assets/19350246/15937773/1fd9d1e0-2e25-11e6-953d-763c4cf4b550.png)

![7](https://cloud.githubusercontent.com/assets/19350246/15937756/09c3a1e2-2e25-11e6-8c2d-5f38ec03e19f.png)

![5](https://cloud.githubusercontent.com/assets/19350246/15937741/f9ffaba2-2e24-11e6-89ff-01b594f2baf3.png)
![6](https://cloud.githubusercontent.com/assets/19350246/15937744/ff4a5080-2e24-11e6-90cb-dae260526184.png)

![prototype1](https://cloud.githubusercontent.com/assets/19350246/15937630/8859e594-2e24-11e6-8057-e6708ad46799.png)
![3](https://cloud.githubusercontent.com/assets/19350246/15937672/a7af0578-2e24-11e6-8b26-a3a2a736db34.png)
![4](https://cloud.githubusercontent.com/assets/19350246/15937735/f22baf5c-2e24-11e6-930b-a76b81104ed0.png)
![8](https://cloud.githubusercontent.com/assets/19350246/15937800/3af2e066-2e25-11e6-86c5-990fd4e4227d.png)
![9](https://cloud.githubusercontent.com/assets/19350246/15937809/3f50d4b0-2e25-11e6-9269-4bb8855200cf.png)
![10](https://cloud.githubusercontent.com/assets/19350246/15937835/561ce1a2-2e25-11e6-8285-041179987a0c.png)
 these are all pictures of prototype i hope you like it this is very unique idea .
