### ISSUE TITLE
Technology challenge idea 

### ISSUE THREAD

**Issue by dube2** [mozilla/TBTWBuildChallenge#73]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: 
  Security Achievers 
- Challenge Contact Person Name: Nqaba 
- Campus Name: University Of Fort hare 
### Idea Description

As a team we discovered that most people are not well educated about the significance of internet security.Hence our idea is that we put extra effort on educating people with internet security and we suggest that you help us with assistance especial the presence of the Team Coach.

_Please answer all of the questions below._
- Idea name:
  Motivating people 
- What is the problem you are solving for:
  Lack of security knowledge when browsing.
- Who encounters that problem (who is your audience - describe them): 
  They are  not well educated about the significance of internet security
- How will your tool solve this problem for these people:  
  Motivating people  about the importance of securing their online life.
- What are you going to create (app, add-on, extension, etc.): 
  We are planning to create an extension 
- What are the next steps for building this tool: 
- Links to additional information:

**Comment by LucyeoH-zz** [comment]
Reviewers: @brianking and @bacharakis

**Comment by brianking** [comment]
Hi @dube2 

There is too little information for us to evaluate this idea. Some examples of the types of information we would need:
- How specifically will you educate people? i.e. what sort of information or other mechanism will you provide?
- What will the extension do?
- Who are the audiences you are targeting?

**Comment by dube2** [comment]
Well l will educate people by encouraging them to be cautious when using the internet particularly making sure that everyone who is using the internet on school computer lab is given flyers or rather small booklets with detailed information on the issues surrounding privacy.For instance how to use privacy settings on social networks and also by checking privacy policy statements which include issues that surrounds  who is collecting your information.

**Comment by LucyeoH-zz** [comment]
@dube2 Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @dube2,

Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
