### ISSUE TITLE
Team Futmites : Technology Build Challenge Idea.

### ISSUE THREAD

**Issue by Emmasimeon** [mozilla/TBTWBuildChallenge#74]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Team Futmites
- Challenge Contact Person Name: Tayo Fagbohun
- Campus Name: Federal University of Technology, Minna
### Idea Description

_Please answer all of the questions below._
- Idea name: Secure Password Store Using Biometric Authentication
- What is the problem you are solving for: Generating, Retrieving and Keeping Secure Password
- Who encounters that problem (who is your audience - describe them): Average Internet Users with Vulnerable and Weak Password.
- How will your tool solve this problem for these people:  Enable People use very secure password and easily retrieving those password without the need to Memorize them.
- What are you going to create (app, add-on, extension, etc.): Web Application
- What are the next steps for building this tool:  Start Design and Code.
- Links to additional information: Nil.

**Comment by LucyeoH-zz** [comment]
Reviewer: @brianking

**Comment by brianking** [comment]
Hi @Emmasimeon 

Thanks for the submission. Right now there is too little information for us to evaluate. 'Biometric Authentication' peaks my curiosity, but you do not say how you are going to use it. 'Enable People use very secure password and easily retrieving those password without the need to Memorize them' also does not reveal much.

Let us know more specifics and we'll give feedback.

**Comment by Emmasimeon** [comment]
This is a web application linked to a database (Password Manager)where people store there password just like KeePass, but this time its not a standalone application its a Web Application running on a remote server and universally accessible to users and makes using of a Passphrase and Fingerprints authentication, instead of the conventional master password used my most users, Because once the master password is compromise the user is in a great risk of danger.
Hope this help..

**Comment by brianking** [comment]
So just to be clear ... all site passwords are stored on a server somewhere, and you can retrieve them when needed using fingerprint recognition? If so a couple of more questions:
- what security model would you use for storing passwords on the server? It seems like a temping target for hackers.
- Do you only aim to cater for devices with fingerprint sensors right now? It's a small (but growing) market.

**Comment by LucyeoH-zz** [comment]
@Emmasimeon  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @Emmasimeon!

Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.

**Comment by Emmasimeon** [comment]
@brianking Basically the Password  are going to be encrypted before been stored using the Rijndael Advanced Encryption Standard and Yes, we working and hope to cater for Devices with fingerprint sensors right now and Computers that supports external/USB fingerprint sensors.
