### ISSUE TITLE
RESEC - Reward For Being Secure

### ISSUE THREAD

**Issue by manishapadhi1** [mozilla/TBTWBuildChallenge#76]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Paranoia 
- Challenge Contact Person Name:  Santosh Bharadwaj Rangavajjula
- Campus Name: Blekinge Tekniska Hogskola (BTH), Karlskrona, Sweden

*Team Members: Bharadwaj, Pratheek, Siddhartha, Shivakanth
### Idea Description

_Please answer all of the questions below._
- Idea name: RESEC
- What is the problem you are solving for: Increasing user Awareness for security and privacy challenges.
- Who encounters that problem (who is your audience - describe them): End users.
- How will your tool solve this problem for these people:  The tool is an application combined with an add-on that will reward users with points for being secure and also helping others to be secure over the web. With the instant feedback and rewarding, we aim to encourage users to inculcate a secure behaviour over the web.  The reward points can be redeemed at merchant outlets, giving us a nice business model. 
- What are you going to create (app, add-on, extension, etc.): App and add-on
- What are the next steps for building this tool: 
  Brainstorming, designing GUI for the app, prototyping the app, designing the add-on, testing prototypes in different batches of participants, Summarising results and documentation.   
- Links to additional information: 
  Attached PPT for an abstract idea on the concept.
  [RESEC.pptx](https://github.com/mozilla/TBTWBuildChallenge/files/264018/RESEC.pptx)

**Comment by LucyeoH-zz** [comment]
Reviewers: @brianking and @bacharakis

**Comment by bacharakis** [comment]
WOW! You have a presentation attached, that's fancy! Congratulations and thank you for your submission.

Can you please share some more technical details on how exactly you will identify if a user is secure or not, in order to reward him/her?!

Looking forward for your reply.

**Comment by realnotvibe** [comment]
Hello Christos !

We are happy that you liked our concept. We identify a user with his
account associated to browser (extension), desktop app and mobile app. We
then take mac address of the devices as input to our apps and store it with
the profile.  The app we design is capable of running a privacy scan . For
example the outdated OS or Browsers. We then notify the user to update them
and reward them points into their account once update is successful. The
primary concern is that we haven't completed our first prototype and still
figuring out. But, we can discuss more about this over the phone (+46
767852126) or Skype call ? as its easy for me to explain it to you.
Anyways, we are in process in rolling out our mockups soon .

-Rgds
-Bharadwaj

**Comment by LucyeoH-zz** [comment]
@rsbth  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @rsbth!

Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful tools for taking your idea to the next level.
