### ISSUE TITLE
Technology Privacy

### ISSUE THREAD

**Issue by Rishabhshivhare** [mozilla/TBTWBuildChallenge#77]
Please answer all of the questions below.

```
Team Name: Aryans

Challenge Contact Person Name: Rishabh shivhare
Campus Name: Arya college of Engineering & IT
```

Idea Description

Please answer all of the questions below.

```
Idea name: Password Generator

What is the problem you are solving for: The need to understand the ways personal(password) data is crawled, stored and used on the web.

Who encounters that problem (who is your audience - describe them): The problem focuses on people of all ages.

How will your tool solve this problem for these people: The tool is an extension or a plugin that keeps a info about the sign up data for the site being visited by the user, it's generate the  password value and pops up an alert when a sign up page is open and fill the password. It keeps password & the personal details provided by the user and consumed by the site and the way it may be used further in the future. It keeps a note of the way the sites may access data from my tool and memory and give us privacy feature..

What are you going to create (app, add-on, extension, etc.): Extension

What are the next steps for building this tool: The coding for the extension.

Links to additional information:
```

@Rishabhshivhare

**Comment by LucyeoH-zz** [comment]
Reviewers: @brianking and @bacharakis

**Comment by bacharakis** [comment]
HI @Rishabhshivhare and thanks for the idea!

Might if I ask what is the difference between your proposal and the standard password manager Firefox has?
Looking forward for your reply!

**Comment by Rishabhshivhare** [comment]
Hi

First of all Thanks for this. Find the attach for details

On Tue, May 24, 2016 at 3:14 AM, Christos Bacharakis <
notifications@github.com> wrote:

> HI @Rishabhshivhare https://github.com/Rishabhshivhare and thanks for
> the idea!
> 
> Might if I ask what is the difference between your proposal and the
> standard password manager Firefox has?
> Looking forward for your reply!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/TBTWBuildChallenge/issues/77#issuecomment-221105553

## 

Rishabh shivhare
Arya college of Engineering & IT

**Comment by bacharakis** [comment]
Hi @Rishabhshivhare , sorry but I can't find a file attached :(

Looking forward for your reply!

**Comment by LucyeoH-zz** [comment]
@Rishabhshivhare  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by Rishabhshivhare** [comment]
[Firefox Built.docx](https://github.com/mozilla/TBTWBuildChallenge/files/292731/Firefox.Built.docx)

hey bacharakis
This is attach file.

**Comment by charissalaisy** [comment]
@Rishabhshivhare,

Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful tools for taking your idea to the next level.
