### ISSUE TITLE
Build Technology Idea Submission [ Fullmoon]

### ISSUE THREAD

**Issue by rjrajivjha** [mozilla/TBTWBuildChallenge#8]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: Wings of fire, USICT, New Delhi, India.
- Challenge Contact Person Name:  Rajiv kumar Jha
- Campus Name:  University School of Information and Communication Technology.
### Idea Description

_Please answer all of the questions below._
- Idea name: **Fullmoon**
- What is the problem you are solving for: Fullmoon will provide a platform to share the privacy issues, faced by people from different part of world. Fullmoon is also providing anonymity to the users. Fullmoon will report to the concerned organizations about the issues faced by users online, protecting their identity. In future, Fullmoon will act as an organization which will serve to protect the web privacy of online population. 

Virtual world is getting into darkness with each passing day. Fullmoon will lighten it, it will spread the light of privacy, light the lamp of knowledge.  
- Who encounters that problem (who is your audience - describe them): Users of virtual Internet world.
- How will your tool solve this problem for these people:   People will share the problem they faced while being online. Fullmoon will contact with the concerned organizations and will help the orgs. and cyber officials to solve the issue asap.
  Fullmoon Blog will let the user know about all the privacy concerns faced by people being online. I t will acknowledge every other issue, which will keep the user awakened.
- What are you going to create (app, add-on, extension, etc.):  A website and an Application.
- What are the next steps for building this tool:  Wire-frame , data flow diagram and algorithm. 
- Links to additional information: None.

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @ScottDowne

**Comment by abbycabs** [comment]
Hi @rajivjhaimin, thanks for the project idea! Sounds like you want to build a community around web privacy - that's great! This looks like a huge undertaking including a blog, privacy awareness content, a communication app and website. Would it make sense to start your community by using the existing tools and channels mozilla has around privacy instead of creating your own from scratch?

**Comment by charissalaisy** [comment]
@rajivjhaimin 

Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about here: https://hackdesign.org/lessons/10. 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @rajivjhaimin! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.
