### ISSUE TITLE
add on for search history

### ISSUE THREAD

**Issue by jazzleen** [mozilla/TBTWBuildChallenge#80]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: 
  star
- Challenge Contact Person Name: 
- Campus Name: mody university
### Idea Description

_Please answer all of the questions below._
- Idea name:search history reinvention
- What is the problem you are solving for:we need to go again and again to search history for viewing our searches instead if we just have an add-on on firefox who allows us to open our search history on webpage itself or we can have an add on button on toolbar which will directly open our search history or delete one's search history . 
- Who encounters that problem (who is your audience - describe them): 
  shahbhaz alam -our mentor
- How will your tool solve this problem for these people:  people dont need to go again and again for viewing or deleting their search histories infact, they have have add on button for deletion or viewing on toolbar itself.
- What are you going to create (app, add-on, extension, etc.): 
  add-on
- What are the next steps for building this tool: next step will be to build an addon for firefox
- Links to additional information:

**Comment by bacharakis** [comment]
Hi @jazzleen and thanks for this extremely interesting idea!

I find it extremely useful and I believe it can has impact but I would like to know more on how it can promote the campaign's specific mission around privacy?!

**Comment by LucyeoH-zz** [comment]
@jazzleen  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll use the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @jazzleen!

Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful tools for taking your idea to the next level.

**Comment by jazzleen** [comment]
Hello mam
Can we get some more time to work on this build up technology.
I hope you'll grant us the time .

**Comment by bacharakis** [comment]
HI @jazzleen !

Did you manage to find some time to work in your idea? We are interested to see your prototype!
Cheers
