### ISSUE TITLE
Tor'red

### ISSUE THREAD

**Issue by ashwinvasudevan** [mozilla/TBTWBuildChallenge#81]
# Build Technology Idea Submission
- Please answer all of the questions below.*
-  Team Name: Easwari Engineering Collge, Firefox Students group
- Challenge Contact Person Name: Ashwin Vasudevan
- Campus Name: Easwari Engineering College
### Idea Description
- Please answer all of the questions below.*
- Idea name: Tor'red
- What is the problem you are solving for: To protect ourselves from hackers from learning about our online activities even when connected to a public network.
- Who encounters that problem (who is your audience - describe them): Media persons, Journalists, Whistle Blowers, every one who is concerned about privacy.
- How will your tool solve this problem for these people: The idea is to provide a portable ,plug and play router that will create a VPN connection. This connection will encrypt all the traffic that flows through it so that its impossible for hackers to sniff our online history 
  What are you going to create (app, add-on, extension, etc.): hardware/app
- What are the next steps for building this tool: Enhancing encryption,Torification of the connection.

**Comment by LucyeoH-zz** [comment]
@ashwinvasudevan  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!
