### ISSUE TITLE
 cyber-pol

### ISSUE THREAD

**Issue by ashwinvasudevan** [mozilla/TBTWBuildChallenge#82]
# Build Technology Idea Submission

​_Please answer all of the questions below._​
- Team Name: Easwari Engineering Collge, Firefox Students group
- Challenge Contact Person Name: Ashwin Vasudevan
- Campus Name: Easwari Engineering College
### Idea Description

​_Please answer all of the questions below._​
- Idea name: cyber-pol
- What is the problem you are solving for:  People unknowing grant permissions for a malicious app/websites which can easily put the user under risk. We will be developing an app and add-on to notify and to revoke unnecessary permissions

Who encounters that problem (who is your audience - describe them): ALL smartphone users.
- How will your tool solve this problem for these people: Our app/add-on will log and notify the user when any app/website tries to access a resource in the background(apps/websites can be white-listed). If the user is suspicious they can report the app/website and revoke its permission/uninstall. These anonymous reports shall be used to warn other users about the app/website
- What are you going to create (app, add-on, extension, etc.):  App/add-on
- What are the next steps for building this tool: automatic blocking

**Comment by LucyeoH-zz** [comment]
@ashwinvasudevan  Thanks so much for this submission! We’re excited to hear about your idea and hope you’ll go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @ashwinvasudevan!

Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful tools for taking your idea to the next level.
