### ISSUE TITLE
How Many Resources - Browser Extension

### ISSUE THREAD

**Issue by Mte90** [mozilla/TBTWBuildChallenge#83]
# Build Technology Idea Submission
### Idea Description

As Local Coach to promote for my teams I have made this browser extension prototype to show all the resources loaded in a page.
- Idea name: How Many Resources
- What is the problem you are solving for: Understand the amount of external resources that a web page can contain
- How will your tool solve this problem for these people: Like Privacy Badger that show the third part providers, with these it is possible see all the resources
- What are you going to create (app, add-on, extension, etc.): Extension
- What are the next steps for building this tool: Hacking for everyone interested in the project and discover how it is easy
- Links to additional information: https://github.com/Mte90/how-many-resources

**Comment by LucyeoH-zz** [comment]
@Mte90 Thanks so much for this submission! We’re excited to hear about your idea and hope go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10). 

Over the next few weeks we will share a number of resources to help you build your prototype. 

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th. 

We can’t wait to see what you create!

**Comment by Mte90** [comment]
The extension it is working without problems, need to improved for the ui/ux so for new contributors is not difficult to improve.

The code is already available with the instructions to try it on Firefox and Chrome.

I don't think actually that my teams can work on that, they are focusing on the other workshops but can interesting for the other teams that participate in that campaign.
