### ISSUE TITLE
Advertisement Predictor - a new way to solve the problem of redirect links

### ISSUE THREAD

**Issue by scha11a** [mozilla/TBTWBuildChallenge#9]
# Build Technology Idea Submission

_Please answer all of the questions below._
- Team Name: SandBoats
- Challenge Contact Person Name: Akhil Koundinya
- Campus Name: JB Institute of Engineering and Technology
### Idea Description

_Please answer all of the questions below._
- Idea name: Advertisement Predictor
- What is the problem you are solving for: 
  Unwanted advertisement redirect links pop up automatically while browsing web, as a response to button clicks,etc...
- Who encounters that problem (who is your audience - describe them): 
  Every user browsing web is facing the trouble of unwanted advertisement pages(redirected links) even after using AD BLOCKERS. 
- How will your tool solve this problem for these people:  
  As we know buttons or other items on webpage will redirect to other wanted or unwanted links. So, even before clicking them if the use hover over the item(buttons, etc..), there will be a floating notification(indicator) at some part of the web browser. This indicator will tell the page(s) you will be redirected to. And you may decide which ever page(s) you wanted to permit. We may also suggest the safer links to the user by adding a marker on the item (if necessary).
- What are you going to create (app, add-on, extension, etc.): 
  An Add-on for a browser. An app for a mobile if resources available.
- What are the next steps for building this tool: 
  I have to gather knowledge and support for the better implementation of the idea. I am new to making add-ons. So, feasibilitiy factor must be improved.
- Links to additional information: 
  None yet.

**Comment by LucyeoH-zz** [comment]
Reviewers: @acabunoc @ScottDowne

**Comment by ScottDowne** [comment]
Is there a reason why ad blockers don't do this?

I also wonder if it'll be easy enough for a malicious link to hide it's location from the addon?

**Comment by scha11a** [comment]
Thank you sir for the support,

This extension will provide "**freedom of choice**", by allowing the users to choose the link they wanted to get redirected, Instead of falling prey to the unwanted links who want to improve their site rank(related to SEO). 

I think Add blockers cannot avoid the users to visit them, because they just **void** the in-page ads but not the ad links behind the buttons, redirect links, etc.

I am thinking to show a bit of content(redirected page title,...etc that which user may be able to recognize the good link from ad link) related to the redirected pages (listed along with check boxes) in an alert box or much better user interface like a balloon pop up just adjacent to the button or redirect inks, etc. so, the user can check mark the link they want to visit.

I am new to making extensions but had good experience in developing iOS applications. Can you please help me in making this idea in a better way by adding corrections to the idea. Because, i don't know how to get the content from the link before visiting them,i.e to show the users about the redirected web link in the alert box.

**Comment by abbycabs** [comment]
Thanks @akhilkoundinya! I think that ad blocker do a good job of **removing** all ads including links. But you have an interesting idea around giving users more information about the ads instead of removing them.

Have you done any user research to see if users would rather have the choice of clicking an ad vs. not seeing ads entirely? Personally, I would prefer to just use  ad blocker.

**Comment by charissalaisy** [comment]
@akhilkoundinya, thanks so much for this submission! We’re excited to hear about your idea and hope you’ll take the feedback you got to go on to the next phase by turning this into a prototype.

A prototype can come in many different forms, some of which you can read about [here](https://hackdesign.org/lessons/10).

Over the next few weeks we will share a number of resources to help you build your prototype.

Once your prototype is ready please link your picture, slideshow, code right here in your issue by June 10th.

We can’t wait to see what you create!

**Comment by charissalaisy** [comment]
Hey @akhilkoundinya! Check out our Take Back the Web resource on [Prototyping for Innovation](https://takebacktheweb.mozilla.community/2016/06/01/prototyping-for-innovation/). It has lots of helpful guidance for taking your idea to the next level.

**Comment by scha11a** [comment]
![webext](https://cloud.githubusercontent.com/assets/10866759/15855851/967e7ed8-2ccf-11e6-9dd0-38ccc2ad614b.png)

The above image is Prototype of my Web Extension Idea.

Once the Web Extension is enabled, the user can hover over the elements using cursor along with long pressing a keyboard key. And hence provide permissions for the browser to surf them by checking radio buttons and click "Go".
